### ISSUE TITLE
Toggle element linking to props

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib-Editor#104]
![an2aipu](https://user-images.githubusercontent.com/23083011/38258070-de3b3b1e-3761-11e8-9817-a47d977baf42.png)

it seems to take the same id from both the mission file and continent.

**Comment by RexTheWho** [comment]
Happens to more than just toggle.

![image](https://user-images.githubusercontent.com/26837908/38675914-e1af96d8-3e8b-11e8-805a-fc02d9d1ad91.png)

Seems to happen after deleting things that had links and making new linkable elements, no repro steps though.

**Comment by RexTheWho** [comment]
I think Ive figured it out.

If an element has the same ID as a unit itll show both are linked, they arent but itll say so.

![image](https://user-images.githubusercontent.com/26837908/38764804-53d7d9b6-3fe8-11e8-9cd7-ee881859ca7c.png)

**Comment by Luffyyy** [comment]
Issue happened because I accidentally included the "elements" key for searching units inside elements will be fixed.
