### ISSUE TITLE
Convex collision is not properly visualised in body view

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#105]
![image](https://user-images.githubusercontent.com/26837908/38323249-4e926d20-386f-11e8-94dd-77ecf17f9c22.png)

With Draw bodies enabled it seems to not show some lines, but ingame you can stand on them and they collide.

Note, this is with a custom collision using triangulated faces.

**Comment by Luffyyy** [comment]
uhhhhh I don't really know if I can do anything
