### ISSUE TITLE
Delete icon 2 times as big if multiple lines

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib-Editor#106]
![70zet5l](https://user-images.githubusercontent.com/23083011/38327909-bf01aa38-3849-11e8-94c2-d1953c0d3d06.png)

**Comment by ontrigger** [comment]
Which unit list is this?

**Comment by Luffyyy** [comment]
Include environments if I'm not wrong

**Comment by Nepgearsy** [comment]
Environment list yeah
