### ISSUE TITLE
Disable On AI Graph doesnt work

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#109]
![image](https://user-images.githubusercontent.com/26837908/38448254-9679f834-3a35-11e8-881d-149e2b4d31ca.png)

This unit wasnt disabled on navigation building even after reloading the map.

**Comment by Nepgearsy** [comment]
think in the meantime try to disable the units instead?

**Comment by Luffyyy** [comment]
Should be fixed in next commit.
todo - #120
