### ISSUE TITLE
Unable to launch project

### ISSUE THREAD

**Issue by LordBoompa** [simon-wh/PAYDAY-2-BeardLib-Editor#11]
When I launch my project, I get an access violation crash during the "loading instances packages" screen. I've tried disabling my mods, but it didn't change anything.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by Luffyyy** [comment]
This is a known issue and sadly I'm unable to do anythign as of now to fix it
if it really doesn't load at all you can send me a link for your map and I'll attempt to fix it

**Comment by LordBoompa** [comment]
I was just able to access my map. I fixed it by adding back all of the packages with props that I had in the map. I removed some packages since I did not need the props from them anymore. I went in safe mode, added back the packages, and did that twice to make sure that was the issue.

**Comment by Luffyyy** [comment]
Oh did you post the full crash because I might have got it confused with a different crash that says nothing about why it crashes(it's a rare one so hard to fix it)
If you see coresystem in crashlog then it's probably crashing when spawning units. 

_Sent from my LGE LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LordBoompa** [comment]
Oh yeah didn't see that part of the crash report, my bad. Here's the rest:


Current thread: Main
Script stack:
                                @mods/BeardLib/Hooks/CoreSystem.lua:24              
                            ()  =(tail                                              
                      call):-1                                                      
@mods/BeardLib-Editor/Hooks/WorldDefinition.lua:411  ()                                                  
                        =(tail  call):-1                                            
                      Create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                      Create()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:48  
                      create()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:48  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:587                        
                                core/lib/setups/coresetup.lua:402                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------


So I suppose it was from spawning units
