### ISSUE TITLE
Element linking issue

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#116]
![image](https://user-images.githubusercontent.com/26837908/38659052-3b6c6958-3e5a-11e8-8782-3f82e77ae2ba.png)

After deleting an element and spawning a new one the issue where an ID is reused happened.

No repro steps yet.

**Comment by Luffyyy** [comment]
Please don't use "issue happened before" I cannot track issues like that, unless you have a link to an issue page which then you can link by typing # and the number of the issue.
Explain the issue in detail.

**Comment by RexTheWho** [comment]
Closed #48 is the same issue

**Comment by Luffyyy** [comment]
Dunno if latest commit could've fixed it, but it fixed an issue where links are not deleted correctly.

**Comment by RexTheWho** [comment]
I havent had it happen since the update, going to close until further notice.
