### ISSUE TITLE
Deleting an instance, element crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#117]
Deleting an instance before removing all links to it will cause a crash on reload of the map.

**Comment by Luffyyy** [comment]
Please provide a crashlog.

**Comment by RexTheWho** [comment]
Application has crashed: C++ exception
[string "core/lib/managers/coreworldinstancemanager.lua"]:521: table index is nil



SCRIPT STACK

init() core/lib/managers/mission/coreelementinstance.lua:123
new() core/lib/utils/coreclass.lua:35
create_element() @mods/BeardLib-Editor/Hooks/MissionManager.lua:536
_create_elements() @mods/BeardLib-Editor/Hooks/MissionManager.lua:525
original() core/lib/managers/mission/coremissionmanager.lua:403
init() @mods/base/req/core/Hooks.lua:185
new() core/lib/utils/coreclass.lua:35
MissionManager_add_script() core/lib/managers/mission/coremissionmanager.lua:113
_add_script() @mods/BeardLib/Hooks/MissionManager.lua:10
_load_mission_file() @mods/BeardLib-Editor/Hooks/MissionManager.lua:93
parse() @mods/BeardLib-Editor/Hooks/MissionManager.lua:45
init_game() lib/setups/gamesetup.lua:642
core/lib/setups/coresetup.lua:405

**Comment by Luffyyy** [comment]
Seems to be an issue where links are removed incorrectly, thanks.
Will be fixed.
