### ISSUE TITLE
Editor launched maps lack preplanning or assets

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#124]
I assume this is used to avoid crashes from changing elements but it would be useful to make sure assets are linked correctly without loading the map properly over and over (even worse on multiday heists)

**Comment by Luffyyy** [comment]
Currently I'm having trouble getting this work, when I try to add narrative to the load it's showing "loading" on assets and some levels seem to crash if I do this.
