### ISSUE TITLE
Units with dest parts

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#132]
Seems there might be an issue loading units that have dest (destruction) units that go with them.

I attempted to load the 2x1 titan safe and then the dest unit that goes with it and resulted in a crash when looking at the spawn units list.

**Comment by Luffyyy** [comment]
Yeah it requires more than that.
Looking at the sequence manager file I can confirm we need to load stuff from there as well.
