### ISSUE TITLE
Error loading environment

### ISSUE THREAD

**Issue by LordBoompa** [simon-wh/PAYDAY-2-BeardLib-Editor#14]
I created an environment, saved it in the editor, and set the environment in the world section. After reloading the map, I keep crashing after a few seconds and I get this error:

Sat Jul 22 12:22:58 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                                35                                                  
                            ()  =(tail                                              
                      call):-1  _load()                                             
core/lib/managers/viewport/environment/coreenvironmentmanager.lua:257  preload_environment()                               
core/lib/managers/viewport/environment/coreenvironmentmanager.lua:107  preload_environment()                               
core/lib/managers/viewport/coreviewportmanager.lua:148  _set_environment()                                  
core/lib/utils/dev/editor/coreworlddefinition.lua:717  WorldDefinition_create_environment()                
core/lib/utils/dev/editor/coreworlddefinition.lua:733  WorldDefinition_create_environment()                
@mods/BeardLib/Hooks/CoreWorldDefinition.lua:90  _create_environment()                               
@mods/BeardLib/Hooks/CoreWorldDefinition.lua:90  Create()                                            
core/lib/utils/dev/editor/coreworlddefinition.lua:485  Create()                                            
@mods/BeardLib-Editor/Hooks/WorldDefinition.lua:49  create()                                            
@mods/BeardLib-Editor/Hooks/WorldDefinition.lua:49  create_world()                                      
core/lib/utils/dev/editor/worldholder.lua:110  init_game()                                         
  lib/setups/gamesetup.lua:587                                                      
core/lib/setups/coresetup.lua:402  ()                                                  
                        =(tail  call):-1                                            

-------------------------------

**Comment by Luffyyy** [comment]
Could you send me the map? sadly I can't do anything without it.

**Comment by LordBoompa** [comment]
[Samurai Infiltration.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1167594/Samurai.Infiltration.zip)

**Comment by Luffyyy** [comment]
You removed some packages(tell me if that's a mistake) and from that the environment that the map had was unloaded + the units that you spawned.
I'll be updating BeardLib to check for environment so next time if it isn't loaded it will use the default environment.

I've loaded you some packages but if you run to that problem again go to safe mode and see if your units are loaded.
http://puu.sh/wQpcg/da24b31290.zip

**Comment by LordBoompa** [comment]
Alright thanks, I had ruled out that problem since I was crashing in safe mode as well.

**Comment by LordBoompa** [comment]
Alright thanks, I had ruled out that problem before since I couldn't load it in safe mode either.
