### ISSUE TITLE
all selectable options inside the search box vanish when scrolling

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#143]
![20180427221210_1](https://user-images.githubusercontent.com/33162051/39392401-01ec4a10-4a6a-11e8-9d28-28aa16beb543.jpg)
this makes selecting units/elements incredibly annoying. doesn't happen with the build that's uploaded on MWS

**Comment by Luffyyy** [comment]
Add more information, where is this list opened from?

**Comment by Whurrhurr** [comment]
anything that involves bringing up this type of search box (managing units/elements pressing V to search for units/elements)

**Comment by Luffyyy** [comment]
Nope, does not happen in my case.

**Comment by RexTheWho** [comment]
This happens when the toggle group button in any UI is not visible.

Video example: https://puu.sh/AdcDx/eeba56e86f.mp4

**Comment by Luffyyy** [comment]
I can swear I've fixed that, have you updated BeardLib?

**Comment by RexTheWho** [comment]
Yes, playing on latest
