### ISSUE TITLE
Crash when attempting to change the default enviornment

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#144]
`Application has crashed: access violation

Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

Current thread: Main
Script stack:
             set_environment()  core/lib/managers/viewport/environment/coreenvironmenthandler.lua:105  
on_default_environment_changed()  core/lib/managers/viewport/environment/coreenvironmenthandler.lua:308  
on_default_environment_changed()  core/lib/managers/viewport/corescriptviewport.lua:97  
     set_default_environment()  core/lib/managers/viewport/coreviewportmanager.lua:195  
                        clbk()  @mods/BeardLib-Editor/Classes/Map/EnvironmentLayerEditor.lua:390  
                 RunCallback()  465                                                 
                    SetValue()  453                                                 
             TextBoxSetValue()  48                                                  
                    SetValue()  58                                                  
                   _callback()  @mods/BeardLib-Editor/Classes/MenuUtils.lua:370     
                        clbk()  167                                                 
                 RunCallback()  465                                                 
                MousePressed()  76                                                  
                MousePressed()  161                                                 
                 mouse_press()  383                                                 
                                lib/managers/mousepointermanager.lua:339`

**Comment by Nolram12345** [comment]
Experiencing this same issue. When trying to load another environment other than the default one, the game crashes.
