### ISSUE TITLE
Crash on viewing units list (custom heist)

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#146]
Application has crashed: C++ exception
Archive::checked_read() Attempt to read past end of archive 'mods/BeardLib//Assets/units/default_cp.cooked_physics'

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  184                                                 
                   LoadAsset()  206                                                 
                   unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:37              
                 GetUnitType()  @mods/BeardLib-Editor/Classes/Utils.lua:532         
                       check()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:187  
                  GetEntries()  @mods/BeardLib-Editor/Classes/Utils.lua:465         
                        clbk()  @mods/BeardLib-Editor/Classes/MenuUtils.lua:362     
                 RunCallback()  468                                                 
                MousePressed()  76                                                  
                MousePressed()  161                                                 
                MousePressed()  161                                                 
                MousePressed()  161                                                 
                 mouse_press()  383                                                 
                                lib/managers/mousepointermanager.lua:339            

-------------------------------

**Comment by Luffyyy** [comment]
I need the project
