### ISSUE TITLE
Alt Duplicating multiple units crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#147]
Created a new level and alt dragged the mkp tile and then alt dragged to 2 new tiles and crashed.

-------------------------------

Current thread: Main
Script stack:
                        clbk()  230                                                 
                        func()  @mods/BeardLib/Core.lua:157                         
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                    original()  @mods/base/lua/GameSetup.lua:6                      
                      update()  @mods/base/req/core/Hooks.lua:260                   
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:540                   

-------------------------------

**Comment by Luffyyy** [comment]
#145.
