### ISSUE TITLE
Disclaimer against playing multiplayer

### ISSUE THREAD

**Issue by Omen267901** [simon-wh/PAYDAY-2-BeardLib-Editor#150]
So, if you have the Editor installed and attempt to play multiplayer, things get fucky. It seems anything with a sequence manager breaks in weird ways, and you become able to walk straight through most things that aren't the core level geometry.

If the host has the editor installed, all clients will have issues, but not the host.
If a client has the editor installed, only that client will have issues.

I'm not sure if this is actually fixable, as to my knowledge it's caused by the SuperBLT patching script being run constantly, even when not in the editor. 

As a result, it'd probably be best to just put a nice big disclaimer warning against playing multiplayer. Something like "IT IS RECOMMENDED TO NOT PLAY MULTIPLAYER WITH THE EDITOR INSTALLED. COLLISION WILL BE BROKEN."

Something else of note is that disabling the editor doesn't fix this. You have to totally remove it from your mods folder. As such, it may be good to mention this in the disclaimer as well. Something to do with the patcher script not caring if the mod's disabled and running anyway is the cause to my knowledge.

**Comment by Luffyyy** [comment]
Removing supermod.xml solves it, for now I'm not gonna do anything with it until I'm capable of making a closed environment for the editor.
