### ISSUE TITLE
Deleting double element crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#151]
If you alt-clone multiple elements that have been placed as editor_only, save, then reload you will have double of the same element with the same id.

Deleting that element and its duplicate will crash.

Note: This also removed elements from my main, this is the same issue from #96 

Application has crashed: C++ exception
mods/BeardLib-Editor/Hooks/MissionManager.lua:623: attempt to index a nil value

SCRIPT STACK

delete_element() @mods/BeardLib-Editor/Hooks/MissionManager.lua:229
DeleteUnit() @mods/BeardLib-Editor/Classes/MapEditor.lua:241
@mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:911
clbk() 178
RunCallback() 468
KeyPressed() 59
299

**Comment by Luffyyy** [comment]
I tried some things in the last update, not sure if it helped, try checking the editor console for errors when deleting units.
