### ISSUE TITLE
Lighting seems inaccurate

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#153]
Lighting doesnt seem to apply the right sizes ingame.
This light has 6400 units far range.

![image](https://user-images.githubusercontent.com/26837908/39506499-7762d7a6-4e0b-11e8-8abd-95d80c169580.png)

**Comment by Luffyyy** [comment]
Dunno that's how the light works 🤷‍♂️
