### ISSUE TITLE
Crash when entering testing mode while saving

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#156]
Pressing F10 while saving can cause this crash. (Done with binary saving)
-------------------------------

Current thread: Main
Script stack:
                 on_executed()  lib/managers/mission/elementnavobstacle.lua:52      
         execute_on_executed()  core/lib/managers/mission/coremissionscriptelement.lua:209  
_trigger_execute_on_executed()  core/lib/managers/mission/coremissionscriptelement.lua:147  
                 on_executed()  core/lib/managers/mission/coremissionscriptelement.lua:131  
                 on_executed()  lib/managers/mission/missionscriptelement.lua:18    
        _on_script_activated()  core/lib/managers/mission/coremissionmanager.lua:514  
                    activate()  core/lib/managers/mission/coremissionmanager.lua:505  
                    activate()  lib/managers/missionmanager.lua:437                 
             activate_script()  core/lib/managers/mission/coremissionmanager.lua:154  
             activate_script()  lib/managers/missionmanager.lua:300                 
           _activate_mission()  core/lib/managers/mission/coremissionmanager.lua:137  
                    activate()  @mods/BeardLib-Editor/Hooks/MissionManager.lua:107  
                     at_exit()  @mods/BeardLib-Editor/Hooks/EditorState.lua:27      
                  trans_func()  lib/states/gamestate.lua:14                         
            _do_state_change()  core/lib/utils/game_state_machine/coregamestatemachine.lua:124  
                  end_update()  core/lib/utils/game_state_machine/coregamestatemachine.lua:104  
                  end_update()  lib/setups/setup.lua:899                            
                  end_update()  lib/setups/gamesetup.lua:774                        
                  end_update()  lib/setups/networkgamesetup.lua:33                  
                                core/lib/setups/coresetup.lua:583                   

-------------------------------

Afterwards attempting to load the level will cause crashes.

-------------------------------

Current thread: Main
Script stack:
        _create_statics_unit()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:437  
                      Create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                      Create()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:32  
                      create()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:32  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:638                        
                                core/lib/setups/coresetup.lua:405                   

-------------------------------

**Comment by Luffyyy** [comment]
and... it doesn't happen for me 🤷‍♂️

**Comment by RexTheWho** [comment]
Solved, issue was a navobstacle that wasnt removed from startup and caused startup crashes. Nav obstacle still needs a bunch of background stuff to get working :/
