### ISSUE TITLE
Assets browser crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#158]
Crashed on opening assets browser after adding an effect, might not be related but its what I did.

Application has crashed: C++ exception
.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:142: table index is nil

SCRIPT STACK

show_assets() @mods/BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:161
reload() @mods/BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:772
_Show() @mods/BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:89
update() 140
func() @mods/BeardLib/Core.lua:153
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

**Comment by Luffyyy** [comment]
probably solved
