### ISSUE TITLE
Package loaded list going wild, unit list crashing

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib-Editor#159]
I tried to load the effect snow_box_10x10 from extract, then removed the package that i needed before.
The packages loaded list got all funky (i had pcalls) with the following error : 

03:15:51AM FATAL ERROR:  (..\src\InitiateState.cpp:657) .../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:142: table index is nil

stack traceback:
	.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:142: in function 'new_asset'
	.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:161: in function 'show_assets'
	.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:772: in function 'reload'
	.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:89: in function '_Show'
	[string "--mods/BeardLib/Classes/Dialogs/MenuDialogMan..."]:140: in function 'update'
	mods/BeardLib/Core.lua:153: in function 'func'
	mods/base/req/core/Hooks.lua:109: in function 'Call'
	mods/base/lua/GameSetup.lua:6: in function 'update'
	[string "lib/setups/networkgamesetup.lua"]:21: in function 'update'
	[string "core/lib/setups/coresetup.lua"]:540: in function <[string "core/lib/setups/coresetup.lua"]:462>

Then clicked on the unit list, and got this crash : 

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        load()  lib/managers/dynamicresourcemanager.lua:151         
                  _LoadAsset()  184                                                 
                   LoadAsset()  206                                                 
                   unit_data()  @mods/BeardLib/Hooks/CoreSystem.lua:48              
                 GetUnitType()  @mods/BeardLib-Editor/Classes/Utils.lua:544         
                    GetUnits()  @mods/BeardLib-Editor/Classes/Utils.lua:519         
                        clbk()  @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:871  
                 RunCallback()  470                                                 
                MousePressed()  87                                                  
                MousePressed()  161                                                 
                MousePressed()  161                                                 
                MousePressed()  161                                                 
                 mouse_press()  389                                                 
                lib/managers/mousepointermanager.lua:339``

**Comment by Luffyyy** [comment]
Give me a project
