### ISSUE TITLE
Subtitles [SBLT Module]

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib-Editor#161]
BeardLib version; Latest from GitHub
BeardLib Editor version; Latest from GitHub

I'm trying to use the SuperBLT Sound Module for my heist, and it's working fine, BUT subtitles are not working, (Dialogue Element) I think we're missing with "subtitle_duration" for Module, or something similar, or even you can do soo it'll automatically take the duration of the sound, and it'll set the subtitle duration to the sound duration, I think it's fine.

**Comment by Luffyyy** [comment]
Not an editor issue.
