### ISSUE TITLE
Changing unit continents does not apply correctly

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#162]
For example if I select a unit and then change its continent in the "Continent" dropdown from "world" to for example "art" the unit itself will stay in the world .continent file but in the world.continent file its listed continent is changed.

EG (This is located in the world.continent to be clear)...
```
		<table>
			<unit_data _prev_pos="-200 -1600 0" _prev_rot="0 0 -0 -1" continent="art" local_pos="-400 -3600 0" local_rot="-0 0 0 1" mesh_variation="display_off" name="units/payday2/architecture/mkp/mkp_int_floor_4x4m_a" name_id="mkp_int_floor_4x4m_a_017" position="-200 -1600 0" rotation="0 0 -0 -1" unit_id="300043"/>
		</table>
```

Note: Because of this selecting all units from the world's continents will also select the units from the art continent that I swapped the units to.

**Comment by Luffyyy** [comment]
confirm if last commit fixed this.

**Comment by RexTheWho** [comment]
Did not fix.

Spawning a unit in World sets it to 100000 and then alt-dragging makes that unit 100001, changing its continent from the dropdown from world to editor_only causes its ID to change to 100000 and on reload replaces the first world unit.

**Comment by Luffyyy** [comment]
It doesn't seem to happen, at least from last commit.

**Comment by RexTheWho** [comment]
So far no issues relating to swapping to and from continents.

**Comment by RexTheWho** [comment]
Issue still active.
Alt-Clone a prop in World continent and they changing it to Editor_Only only changes the written continent location, not the physical location.
The prop set to Editor_Only is still located in Worlds continent folder.

**Comment by ontrigger** [comment]
Alright, so I made a quick experimental fix to this on my fork but I'm kind of afraid of pushing it there as I'm not familiar with worlddef logic. It would be great if some of you guys @RexTheWho could download my repo and test if the fix breaks anything. Make sure to backup your map folders!

**Comment by ontrigger** [comment]
Fixed with the latest commit
