### ISSUE TITLE
Briefing crash (Another)

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib-Editor#163]
When the briefing voice-line ends, and you hit Enter, it'll crash with; 
`Application has crashed: C++ exception
mods/base/req/xaudio/XAudioSource.lua:71: Cannot use closed resource!

SCRIPT STACK

stop() @mods/base/req/xaudio/XAudioSource.lua:71
stop_event() lib/managers/voicebriefingmanager.lua:159
sync_start() lib/states/ingamewaitingforplayers.lua:84
_start() lib/states/ingamewaitingforplayers.lua:73
start_game_intro() lib/states/ingamewaitingforplayers.lua:533
check_start_game_intro() lib/network/base/basenetworksession.lua:1666
on_set_member_ready() lib/network/base/hostnetworksession.lua:984
on_ready_pressed() lib/managers/menu/missionbriefinggui.lua:3412
confirm_pressed() lib/managers/menu/missionbriefinggui.lua:3586
confirm_pressed() lib/managers/menu/menucomponentmanager.lua:1207
up() lib/managers/menu/menuinput.lua:738
update() @mods/BeardLib/Hooks/MenuInput.lua:123
update() core/lib/managers/menu/coremenumanager.lua:157
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:837
original() lib/setups/gamesetup.lua:701
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540`

**Comment by Luffyyy** [comment]
Not an editor issue.
