### ISSUE TITLE
Asset menu crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#165]
Opened level in safemode to load in an unloaded unit from extract and crashed.

Application has crashed: C++ exception
.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:219: table index is nil

SCRIPT STACK

RunCallback() 482
MousePressed() 87
MousePressed() 159
MousePressed() 159
mouse_press() 389
lib/managers/mousepointermanager.lua:339

**Comment by Luffyyy** [comment]
Anything related to assets manager mostly require a project, so..

**Comment by RexTheWho** [comment]
Issue was fixed a while ago on my end with no backup, if it happens again Ill send it in.
