### ISSUE TITLE
Game crashes upon loading a specific instance

### ISSUE THREAD

**Issue by Aurimenas** [simon-wh/PAYDAY-2-BeardLib-Editor#17]
The game crashes when loading hox_fbi_powerbox for some reason, here's the log of only that crash provided: 
[2017_07_26_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1175953/2017_07_26_log.txt)

**Comment by Luffyyy** [comment]
That's your log file I asked for crashlog 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Thought this was the kind, uhm, where do I find the crashlogs again? I've tried simply using the search on entire pd2 directory but couldn't find much, should it be named something specific :x ?

**Comment by Luffyyy** [comment]
%localappdata%\PAYDAY 2

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Ah thanks, found it, here it is:
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1175995/crashlog.txt)

**Comment by Luffyyy** [comment]
I only see the vehicle crash can you crash again and send me what's inside crash.txt?

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Sure

**Comment by Aurimenas** [comment]
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1176021/crashlog.txt)
well, this time it was more of a freeze ratherr than a straight up crash/sys_32  close program type of crash but it still happenned at the same point

**Comment by Luffyyy** [comment]
I think that's the vehicle causing the crash try loading the map in safe mode and delete the vehicle using assets manager 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Oh, well, the vehicle crash lets me open the heist itself, its a tiny problem in another heist I'm working on, the biggest concern right now was the hox_fbi_powerbox instance crashing on a project called "dank", if the crashlog gives out names :x

**Comment by Aurimenas** [comment]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                       SHELL32  (???)     Shell_GetCachedImageIndexA                          
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                       SHELL32  (???)     Ordinal93                                           
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 


-------------------------------

Current thread: Main
Script stack:
                       apply()  core/lib/managers/viewport/environment/coreenvironmentfeeder.lua:202  
                       apply()  core/lib/managers/viewport/environment/coreenvironmenthandler.lua:266  
                     _update()  core/lib/managers/viewport/corescriptviewport.lua:286  
                      update()  core/lib/managers/viewport/coreviewportmanager.lua:33  
                                core/lib/setups/coresetup.lua:497                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------

System information:
	Application version : 1.74.281.
	CPU : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960M / nvd3dum.dll[21.21.13.7667]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8108MB 364KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

There's the content of another crash.txt file, I assume it shows the last crash only, don't know if it helps

**Comment by Aurimenas** [comment]
I can also drop the map file folder here if that helps to solve the issue, in worst case scenario, removing the instance would suffice xD, perhaps it was silly to spawn then ahead without considering if I'm 100% sure I'll be using them, they probably overload the system:
[Dank project.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1176310/Dank.project.zip)

**Comment by Luffyyy** [comment]
Dunno it shouldn't have caused any harm I'll see your map when I can I'm currently in vacation so i can't access my pc. 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Aurimenas** [comment]
Alright, thanks fam, enjoy your free time there ;P

**Comment by Aurimenas** [comment]
Found yet another different crash, hoping you dont mind I post it here :/ . It started to occur after I've place an element, unit one but cant remember which one. After that moment, every editor level that's launched crashes before the grey loading screen can finish up. Crash#2 log (sole):
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1177702/crashlog.txt)

**Comment by Luffyyy** [comment]
Same issue as here https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/issues/20#issuecomment-319007395
the fixed main xml: https://www.dropbox.com/s/c7vrdijey8lz66e/main.xml?dl=0

**Comment by Luffyyy** [comment]
I also add that I might add quick buttons for assets manager like remove all packages and that safe mode won't load packages so you can load into there without crashing.
