### ISSUE TITLE
Suggestion: being able to make some units ignored by the unit spawn list

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib-Editor#171]
I'm using several units for weapons that have nothing to do with my map, and they are appearing in the unit spawn list and unit loaded list, which makes a mess

Being able to precise which units we want to be ignored by the map assets in the xml would be nice

**Comment by RexTheWho** [comment]
Also hiding core units the editor uses would be good too, I often click them by mistake and some will crash you if you try to spawn them.
