### ISSUE TITLE
Extract loading "No assets to copy" bug

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#173]
If you say cancel to loading from extract the unit will be added but then attempting to properly load the unit it will say "No assets to copy" and you will not be able to spawn the unit. 

Edit: Not being able to spawn it isnt constant, sometimes they show on list sometimes they dont.

**Comment by Luffyyy** [comment]
BeardLib bug, will be fixed.
