### ISSUE TITLE
Crash on spawning element rotateunit

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#174]
Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/MenuUtils.lua:223: attempt to call a nil value

SCRIPT STACK

update_positions() @mods/BeardLib-Editor/Classes/Map/Elements/moveunitelement.lua:109
_build_panel() @mods/BeardLib-Editor/Classes/Map/Elements/moveunitelement.lua:158
work() @mods/BeardLib-Editor/Classes/Map/MissionScriptEditor.lua:39
set_element() @mods/BeardLib-Editor/Classes/Map/MissionEditor.lua:77
set_selected_unit() @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:717
add_element() @mods/BeardLib-Editor/Classes/Map/MissionEditor.lua:106
add_element() @mods/BeardLib-Editor/Classes/MapEditor.lua:459
mouse_pressed() @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:624
mouse_press() @mods/BeardLib-Editor/Classes/MapEditor.lua:200
mouse_press() 395
lib/managers/mousepointermanager.lua:339

**Comment by Luffyyy** [comment]
Fixed, warning you that it's not exactly intended to be used as much as I'm not so sure how functional it is.
