### ISSUE TITLE
Light distance doesnt seem correct

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#181]
I think I brought this up before but Im still not convinced this is correct, this image shows the lights should show at 366cm but in the radius no light can be seen.

![image](https://user-images.githubusercontent.com/26837908/40122210-df971d0a-5955-11e8-8cf6-9d06a6c98494.png)

This is what the default light should look like at 366cm.
![image](https://user-images.githubusercontent.com/26837908/40124183-8e9229c2-595a-11e8-8f66-c57703b6d2e3.png)

**Comment by Luffyyy** [comment]
Dunno, I think it's more an engine issue? or some setting is different in your case?

**Comment by RexTheWho** [comment]
Figured something out.
light_omni_shadow_projection_01 have a small light area for some reason.
light_omni_01 have proper light size

**Comment by Luffyyy** [comment]
Seems to me more an engine issue than editor
