### ISSUE TITLE
add.xml's copied over from other projects don't actually load any of the units from the xml

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#184]
copying over add.xml (or just copying the file and pasting it to overwrite a new project's add.xml) will show that it loads the units from add.xml when you look in Assets, but you can't see any of the units loaded from add.xml. 
![20180516154418_1](https://user-images.githubusercontent.com/33162051/40149480-c31faa2a-5928-11e8-9f4b-b0f4a43e7afe.jpg)
units are loaded according to this
![20180516164746_1](https://user-images.githubusercontent.com/33162051/40149508-e5023464-5928-11e8-990a-3ae7a500d6ff.jpg)
...but they're not actually loaded at all.

**Comment by Luffyyy** [comment]
lol
