### ISSUE TITLE
CounterReset Element not showing in selection pane when selected.

### ISSUE THREAD

**Issue by DiscendoVox** [simon-wh/PAYDAY-2-BeardLib-Editor#185]
Replicated in a couple heists. I have not experimented with this in great detail. Example image below. Confirmed by other users.

https://steamcommunity.com/sharedfiles/filedetails/?id=1387579346

**Comment by Luffyyy** [comment]
Yeah normally the editor should've opened this dialog 
![image](https://user-images.githubusercontent.com/11510099/40237115-24230c00-5ab8-11e8-8335-059f0f6e15cd.png) 
now it will show that, you can just press yes and it will open a page in here to open an issue.
I'll also add this element, thanks for reporting.
