### ISSUE TITLE
Suggestion: allow users to manually enter a value for "Sky Rotation" instead of using a slider

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#186]
currently the only way to change sky rotation is with a slider that can go from 0.000 to 360.000 and doesn't allow for some rotation values (you can only go up or down by 4.794 on 1360x768). allowing users to enter a value between 0.000 and 360.000 by pressing LMB/Left click on "Sky Rotation" would allow the user to use sky rotation values they can't use because of the slider.

**Comment by Luffyyy** [comment]
I'm pretty sure you just have to right click the textbox.
