### ISSUE TITLE
Suggestion: Orthographic options

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#190]
I think I suggested a few Ortho stuff before but Ill pile up all the ortho related ones here.

-Orthographic zoom bar: Let us type in an exact amount to zoom, this lets us get unit to pixel scaling.

-Ortho Rotation: For example if I wanted to take a screenshot of my level from top-down but because of the angle I made my level I cant get the tall level to show on my wide screen fully.

**Comment by Luffyyy** [comment]
Moved to https://feathub.com/simon-wh/PAYDAY-2-BeardLib-Editor
