### ISSUE TITLE
Stacking UI bug

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#191]
If you open for example a unitsequence menu and select a drop down then press B (or whatever keybinds that will open a new menu over it) then esc to leave it and you will have stacking dropdowns.
![image](https://user-images.githubusercontent.com/26837908/40221438-0cba077a-5aaf-11e8-9c04-c0783d9db719.png)

**Comment by Luffyyy** [comment]
Try to understand sometimes when it's a BeardLib issue and not editor, most of the UI is BeardLib itself.
I'll fix it.
