### ISSUE TITLE
Crash in package selector

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#194]
Repro steps:
1. Load Unit
2. Select any unit
3. Dont move your mouse and press enter
4. Crash

Application has crashed: C++ exception
.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:684: attempt to concatenate local 'package' (a nil value)

SCRIPT STACK

_callback() @mods/BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:253
clbk() 167
RunCallback() 485
KeyPressed() 59
305

-------------------------------

**Comment by Luffyyy** [comment]
Cannot reproduce.

**Comment by RexTheWho** [comment]
Example video: https://puu.sh/Apu3I/a7e2544ee9.mp4
Note first try I moved my mouse so I went back a step to not move my mouse at all

Same crash as before.

Application has crashed: C++ exception
.../BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:684: attempt to concatenate local 'package' (a nil value)



SCRIPT STACK

_callback() @mods/BeardLib-Editor/Classes/Dialogs/AssetsManagerDialog.lua:253
clbk() 167
RunCallback() 485
KeyPressed() 59
305

**Comment by Luffyyy** [comment]
Doesn't happen. Try force updating both editor and beardlib.

**Comment by RexTheWho** [comment]
On latest, still happens.

**Comment by Luffyyy** [comment]
BeardLib issue, update it.
