### ISSUE TITLE
Levels loaded through "levels" take me to the default screen with infinite loading times

### ISSUE THREAD

**Issue by Dilbert-JonhonsonThe999th** [simon-wh/PAYDAY-2-BeardLib-Editor#197]
This may be a rookie mistake, as I may have done something incorrectly while setting up my level. I have all my mods removed, but yet when I go to try and select a level it asks me if I want to load it. If I press Yes, it takes me to the "waiting for response" loading thing and then puts me in the default briefing scene. If I click "ready", it will load, but infinitely. Pressing "Toggle GUI" and "Toggle Editor" both don't work.

My game files are in assets/extract (just a default extract from the Bundle Modder)

**Comment by Luffyyy** [comment]
was fixed in the latest build on github, I recommend getting the version from there.
