### ISSUE TITLE
Double package and invisible cross

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#198]
See image.
You can select the same package twice.

![image](https://user-images.githubusercontent.com/26837908/40276282-95bd3396-5c38-11e8-9309-cb210bc1361d.png)

**Comment by Luffyyy** [comment]
Pretty sure you can't select the same package, how did you do that?

**Comment by RexTheWho** [comment]
Just select the same unit to be added twice, nothing stops you

**Comment by Luffyyy** [comment]
ah welp two of the same package shouldn't really hurt, but if it does tell me.

**Comment by Luffyyy** [comment]
Update BeardLib for the GUI bug though.
