### ISSUE TITLE
[Updated] Application Crash While Decrypting Files + Suggestion

### ISSUE THREAD

**Issue by TheRealDannyyy** [simon-wh/PAYDAY-2-BeardLib-Editor#2]
**General Information:**
I've recently found out about this amazing mod and I have to say that it's pretty impressive. 
I could setup everything just fine and it works for the most part (Beardlib + Editor + Extensions).
My map is basically _four stores_ without cars and trees, just a quick test.

**Problem Description:**
Now to my problem. I've done the mapping and I would like to decrypt my files now, to load and play my map (I assume that's how it works, the documentation is lacking **_a lot_** of information about the whole process). However as soon as I start the decryption process and try to convert _world.mission from BINARY to GENERIC_XML_ and _world.continent from BINARY to CUSTOM_XML_, my game crashes.

**Observed Result:** Payday 2 crashes while decrypting the world.mission and world.continent files to the XML format that is required in order for maps to work.

**Expected Result:** Payday 2 shouldn't crash and convert the files as intended.

**Attachments:**
**~** [Crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/829315/Crashlog.txt)

**Comment by TheRealDannyyy** [comment]
**Edit:**
Nevermind I was following an outdated tutorial, the majority of the stuff mentioned in there was for the version without the actual editor.

**Suggestion:**
I would nonetheless appreciate if you guys could simplify the whole process of creating maps. Especially beginners like me are having a difficult time figuring out things like, how to create the main.xml file and how to include assets and so on. It would be great if you modders could automate the creation process even further. This would give beginners the opportunity to do mapdesign changes to maps while keeping the main mechanics (tasks) of a map.

**Comment by Luffyyy** [comment]
The crash happens because overkill changed something that causes now crashes when trying to read unloaded script data, yes you need the main.xml for maps to work and yes next versions will have the process of creating new clean levels automatically done, you will only need to fill a name and you are done.
