### ISSUE TITLE
The level crashes shortly after loading the textures for objects

### ISSUE THREAD

**Issue by BushDidNothingWrong** [simon-wh/PAYDAY-2-BeardLib-Editor#20]
So I was working on this project for days now and suddenly it began crashing without a stop when being launched again and finishes the texture loading phase/sometimes not even till that.
Here's the crashlog info:

Sun Jul 30 18:31:39 2017

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
                      KERNEL32  (???)     ???                                                 
                         ntdll  (???)     ???                                                 
                         ntdll  (???)     ???                                                 

-------------------------------

Current thread: FileStreamer

**Comment by Luffyyy** [comment]
Please send me the map I'll check what's wrong with the level. 

_Sent from my Lge LG-D855 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BushDidNothingWrong** [comment]
Sure, here it is :
[Infiltration project.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1185806/Infiltration.project.zip)

**Comment by BushDidNothingWrong** [comment]
The level seems to work fine now, as another day has come, however, the crash reason remains mysterious, wonder if it could occur again, and whether or not I'd be as fortunate to have it magically disappeared a day later :D

**Comment by Luffyyy** [comment]
Your map has many many packages, I tried to load different ones and it seems to work sadly we don't have any better method of loading units but if it happens again just remove the packages inside the main.xml, load into safe mode and load packages, try to choose the smallest ones and look at their size.
replace your main.xml with this: https://www.dropbox.com/s/xnx2ifxrqsh05oy/main.xml?dl=0
