### ISSUE TITLE
Long FPS drop when opening all packages list

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#201]
FPS drop takes ~20s on my end to open while stopping me from doing anything.

![image](https://user-images.githubusercontent.com/26837908/40289935-c8aa6296-5ced-11e8-8fb8-2f82b2b1ed44.png)

**Comment by Luffyyy** [comment]
Two options:
1. Remove the feature
2. Add a dialog

There's absolutely nothing I can do about it sadly, it has to read the bundle files for sizes, would be probably better to just remove the sizes honestly.
