### ISSUE TITLE
job value filter element seems to be missing

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#202]
"When executed the element will trigger its executions only if the job value matches these settings."

Used to carry an amount of id across to another level with a filter, so if a player has not triggered a job value it the filter would be missing the required ID to be triggered.

Used for Big Oil and Watchdogs for assets and lootbags.

**Comment by Luffyyy** [comment]
Missing from the list, will fix.
