### ISSUE TITLE
Crash on selecting vanilla level lootbag spawner

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#206]
Application has crashed: C++ exception
.../BeardLib-Editor/Classes/Map/Elements/lootbagelement.lua:28: attempt to perform arithmetic on field 'spawn_dir' (a nil value)

SCRIPT STACK

update() /Classes/Map/MissionEditor.lua:115
update() /Classes/MapEditor.lua:550
func() /Core.lua:312
Call() /req/core/Hooks.lua:109
original() /lua/GameSetup.lua:6
update() /req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

Sorry for posting in main not editor, didn't see that.

**Comment by Luffyyy** [comment]
which level?

**Comment by RexTheWho** [comment]
This was watchdogs day2 iirc.
