### ISSUE TITLE
alt-clone unit sequence link issue

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#207]
If you give a single unit sequence element 2 sequences to a single unit (eg this file 001) then alt-clone it you will have one sequence linked to the new unit (file 002) and another the first unit (file 001).

![image](https://user-images.githubusercontent.com/26837908/40320496-8497558e-5d5e-11e8-8e90-836f2c21871b.png)

**Comment by Luffyyy** [comment]
I probably didn't understand it correctly, but trying to link the same unit with different sequences and then alt cloning the **element** seems to keep the links properly.

Only issue I've noticed on my end is that the remove old links option seem to not work, I'll fix that.

**Comment by Luffyyy** [comment]
Huh that's what I said, 1 sequence triggering 1 unit with 2 different sequences to **trigger**.
No I'm 100% not getting this right, explain properly also make sure it happens on latest commit.

**Comment by Luffyyy** [comment]
Another commit pushed that fixed a link issue, dunno if it's this issue.

**Comment by RexTheWho** [comment]
Issue continues, slightly different now

With image linked, "show_file_015" (left side) was linked to do 2 sequences ("show" and "Enable")
Then when I select both and alt-drag all connections are to the original unit.

![image](https://user-images.githubusercontent.com/26837908/40402099-703f4d52-5e7c-11e8-8b8c-a66400251848.png)
![image](https://user-images.githubusercontent.com/26837908/40402113-7a07218e-5e7c-11e8-89d5-e3a00eab8c01.png)

**Comment by RexTheWho** [comment]
And now on reload they're cloning with the link but only 1 sequence is there and the other sequence is missing.

**Comment by Luffyyy** [comment]
I need confirmation that this issue has been fixed.

**Comment by RexTheWho** [comment]
So far seems like its fixed.
