### ISSUE TITLE
SpawnEnemyDummy type issue

### ISSUE THREAD

**Issue by BushDidNothingWrong** [simon-wh/PAYDAY-2-BeardLib-Editor#21]
1. SpawnEnemyDummy element does not have guards in it, only assault units 
1.1. Tried replacing the random swat or whatever unit by hand in world.mission script, by changing to ene_security_2/ene_security_2   but that crashes the game when the level is launched and test mode is launched (F10)
Do I need to manually add npcs to the spawn list somehow?
Edit: may be the special objectives- patrol points I set before the crash occured, but I highly doubt they cause it, the manually replaced apparently non-existent unit is the most obvious reason to me :x

**Comment by Luffyyy** [comment]
You need to load the units from load > units in utilities.

**Comment by BushDidNothingWrong** [comment]
Oh its considered a unit xD, thanks fam
