### ISSUE TITLE
Cubelights not applied

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#211]
Cubelights dont apply properly.

Quote Walrus: It works if I have it like this in the add.xml
texture path="levels/mods/namehere/cube_lights/000001"/

**Comment by RexTheWho** [comment]
Filepath is incorrect.

Generated path:
	<texture path="levels/mods/crk_heliosroom/cubemaps/100050"/>
Proper path:
	<texture path="levels/mods/crk_heliosroom/cube_lights/100050"/>

**Comment by ontrigger** [comment]
whoops, I guess I mistook cubamps for cubelights, super easy to fix
