### ISSUE TITLE
[Maybe not tied to editor] No way to restart after going to safemode

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib-Editor#216]
Basically go in safe mode, then go back in beardlib editor's menu, try to load the same map again in normal mode, it will stuck in a fake loading screen forever (you can even pause the game and the loading symbol just stops)

**Comment by Luffyyy** [comment]
Does not happen.

**Comment by Nepgearsy** [comment]
probably a mod on my end then, ill close that issue
