### ISSUE TITLE
Crash on selecting custom environment through the included environments or through browse

### ISSUE THREAD

**Issue by Dilbert-JonhonsonThe999th** [simon-wh/PAYDAY-2-BeardLib-Editor#217]
Title says it all. I created a custom environment by messing with some settings, thought it looked nice, saved it, and went to open it. However, if I open it it just crashes and reloading the map once back in game shows the default environment.

**Comment by Luffyyy** [comment]
Update through github

**Comment by Dilbert-JonhonsonThe999th** [comment]
Yeah, for some reason the in-game update dialogue for BeardLib downgraded my editor version...
