### ISSUE TITLE
Custom heist randomly crashes before reaching briefing screen; inconsistent

### ISSUE THREAD

**Issue by Dilbert-JonhonsonThe999th** [simon-wh/PAYDAY-2-BeardLib-Editor#218]
about 60% of the time I attempt to play my heist, it crashes before even loading or reaching the briefing screen. I am updated to the newest version (did not use the in game updater) and I really don't have a clue. I don't think it's the packages, since my heist loads fine in the editor, and I don't think it's the scripting since I've been able to play the heist with the exact same scripts before. It began happening after PD2 crashed when opening the editor since I had extra mods installed (which I promptly removed).

**Comment by Luffyyy** [comment]
When it's a heist specific crash it would be better to give me the project files.
You can send me privately in discord if you wish(Luffy#9999)

**Comment by Dilbert-JonhonsonThe999th** [comment]
Sorry 'bout that, I got so frusturated that I deleted beardlib editor (not the map) but when I went to reinstall it something went wrong and I had to wipe my PD2 so the map is kill :(
