### ISSUE TITLE
elements sometimes show as "Linking to" an element but the element that it's linked to doesn't show as being linked by said element

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#219]
i "think" this is related to saving where if you try to link things elements afterwards (only tried it with Manage on executed) there's a very high chance that the elements you link won't actually be linked (they'll show up as linked for the element that's linking to the elements)
![20180601083536_1](https://user-images.githubusercontent.com/33162051/40849734-95e5424e-6577-11e8-9301-8f88288c1c20.jpg)
(element shows as linking to 4 SpawnEnemyDummy's)
![20180601084105_1](https://user-images.githubusercontent.com/33162051/40849755-a49e6284-6577-11e8-915a-01c6ebb6ab33.jpg)
but one of the SpawnEnemyDummy shows that the previous element is not actually linking to it. (i looked at the other 3 linked ones and they also weren't linked by the filter)

**Comment by NoName0D** [comment]
There is already a issue open with that bug 
https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/issues/209
