### ISSUE TITLE
Bad allocation causes crash at loading screen

### ISSUE THREAD

**Issue by BushDidNothingWrong** [simon-wh/PAYDAY-2-BeardLib-Editor#22]
The title says it all, it may be a very silly mistake of me, however, I can't find it (I'm still not experienced enough to know how every piece of code should look), may have missed a slash there or there. Been working on english.txt and main.xml files when the crash began to occur. The log and entire project(if needed and if you could find the specific mistake xD) are here : 
[crashlog.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1203468/crashlog.txt)
[Infiltration_Project.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1203469/Infiltration_Project.zip)
PS: I know you guys are busy, so you needn't rush it if it turns out to be complex, and this is quite a ridiculous reason for an issue post, but this is still causing crashes everytime. #TmwYouSpendMadAmmountOfHoursOnAProjectAndItCrashes

**Comment by Luffyyy** [comment]
Your level seems to be fine?

**Comment by BushDidNothingWrong** [comment]
Fine or not it crashes due to bad allocation :< . You mean there's nothing wrong in the code ;-; ? I may just need to look for my backup version then. rip some progress, but oh well :<

**Comment by Luffyyy** [comment]
You edited script files by yourself when you're not supposed to, if you don't know how to edit xml files then don't.
either way statics in the world continent doesn't have a close, so add </statics> in line 7797.
