### ISSUE TITLE
Editor crashes when making a new level.

### ISSUE THREAD

**Issue by NoName0D** [simon-wh/PAYDAY-2-BeardLib-Editor#223]
Thu Jun 07 15:35:23 2018

Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/MapProjectManager.lua:484: attempt to call method 'InsertNode' (a nil value)

    self._text = nil
end
function InputDialog:hide(yes, ...)

SCRIPT STACK

run_callback() 54
clbk() 163
RunCallback() 485
MousePressed() 87
MousePressed() 162
mouse_press() 410
lib/managers/mousepointermanager.lua:339

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by ontrigger** [comment]
Are you sure you are using the latest BeardLib version from git?

**Comment by NoName0D** [comment]
Ok, i had the lasted ver from modworkshop, after the update to the github ver its working.

**Comment by Luffyyy** [comment]
Hmm I'll update the MWS version I guess.
