### ISSUE TITLE
Physics setting fix/ can't move objects with arrows

### ISSUE THREAD

**Issue by bobost2** [simon-wh/PAYDAY-2-BeardLib-Editor#224]
Where I can find the fix?

**Comment by Luffyyy** [comment]
Install SuperBLT.

**Comment by bobost2** [comment]
Not fixed

**Comment by ontrigger** [comment]
Did you follow the instructions and install it like it told you to?

**Comment by bobost2** [comment]
Is superBLT is the same as BLT, because It gives me that I need to update it and it sends me to BLT site. And also, how the PAYDAY Bundle works? I putted the two rar archives (breadlib + breadlib editor) in the payday bundle/mods and it gives me "The following mod could not be loaded"?

**Comment by bobost2** [comment]
Where I need to extract the files? (directory)

**Comment by ontrigger** [comment]
Download SBLT from https://superblt.znix.xyz, then put the dll file in the root directory of Payday. Delete the base folder inside mods, launch the game, press ok to download the needed files. Now extract the contents of Beardlib and the editor into the mods folder and launch the game.

**Comment by bobost2** [comment]
FIXED! :)
