### ISSUE TITLE
I have a lot of question to ask. Glad you answer it all :)

### ISSUE THREAD

**Issue by bobost2** [simon-wh/PAYDAY-2-BeardLib-Editor#225]
1. Why the detection meter doesn't work when you are detected by a camera? (also it doesn't highlight you when you press F)
2. Why when I add AI the game crashes when killed or saw you?
3. How the interaction with interactable units (such as computers) work with elements? (for example objectives and other stuff when hack is starting and when the hack is completed).
4. How to make AI to look up for the cameras (If the guard is in the security room) and then to kill him to disable the cameras.
5. Escape, loot and other stuff, where to find them?
6. I want an example for localizaton file, because I can't make it correct and that causes the game to crash.

That are my questions for now. Thank you :)

**Comment by bobost2** [comment]
And also
7. How to set the hack time.
8. How to make while hacking to turn off the power for example and then turning on the power

**Comment by Luffyyy** [comment]
This is not a place to ask questions. 

I'm sorry but you'll need to ask somewhere like MWS's discord #help https://discord.gg/Eear4JW
You can also view the MWS wiki: https://modworkshop.net/wiki.php?action=categories&cid=5

I personally will not help you with any problem except a straight crash that is reported properly.
Also avoid reporting a few issues in one issue. I will instantly close the issue if you do that.
