### ISSUE TITLE
detection meter broken?

### ISSUE THREAD

**Issue by bobost2** [simon-wh/PAYDAY-2-BeardLib-Editor#226]
When I download custom heist, the detection meter works, but if I create a heist it doesn't appear on the hud. Also, guards can see trough solid wall with collisions.

**Comment by Luffyyy** [comment]
Don't know about the first issue but the 2nd has to do with navigation afaik but it's not an editor issue. I'm guessing most of those issue you have are just confusion to how the editor works, as much as I'd love to help I'm not a map creator and I'm busy. There are map creators, but a lot refuse to help newbies 😑
