### ISSUE TITLE
Area Triggers don't trigger.

### ISSUE THREAD

**Issue by Booo3** [simon-wh/PAYDAY-2-BeardLib-Editor#227]
I don't know if you are aware of it, but using the "Manage Unit Ids List" grays out the player instigator with no way getting it back [In the editor] so just pressing the option breaks the trigger.
![20180624141136_1](https://user-images.githubusercontent.com/33006056/41818987-7cb3d4c6-77b9-11e8-88b8-7b31966f3e1f.jpg)
![20180624141143_1](https://user-images.githubusercontent.com/33006056/41818994-909e9be2-77b9-11e8-88fb-5a0f583681b6.jpg)
It would be great if you would add a option in editor to remove this state, because i found out by deleting this entry, it fixes the trigger.
![del_this](https://user-images.githubusercontent.com/33006056/41819014-d44fcb9a-77b9-11e8-9463-ad148f4109b7.PNG)
![20180624141445_1](https://user-images.githubusercontent.com/33006056/41819017-dd4594a0-77b9-11e8-963a-5b171ceed4a1.jpg)

**Comment by RexTheWho** [comment]
Still an issue, I've had it catch me off guard multiple times in the past after miss clicking the units list.
