### ISSUE TITLE
Something went wrong with the creation of cubemaps! (Cubemap or Cubelight generation)

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#229]
When generating Cubemaps or Cubelights you get this error message, Tested on a new map.
No Error logs generated in the cubemapgen.log file.

Omnilight being used:
units/lights/light_omni_shadow_projection_01/light_omni_shadow_projection_01

Cubemap Gizmo:
core/units/cubemap_gizmo/cubemap_gizmo

**Comment by ontrigger** [comment]
Cannot reproduce, need more info

**Comment by ontrigger** [comment]
You can try deleting the cubemaplog file, trying again and posting the log here. You could also send the blt log but i doubt that would show anything as it doesnt record the python process output

**Comment by RexTheWho** [comment]
After multiple tries and reinstalls of beardlib + editor still no luck.

**Comment by ontrigger** [comment]
If there is no log (or nothing in the log) then it could be that the python script fails to launch. This could be an issue with your antivirus blocking the execution of the gen_cubemaps file

**Comment by RexTheWho** [comment]
Fixed, Not too sure what I did but downloading latest seems to have cleaned it up.
