### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by duuqnd** [simon-wh/PAYDAY-2-BeardLib-Editor#230]
BeardLib-Editor doesn't seem to work on GNU/Linux. I have BeardLib installed and I'm using SuperBLT.
The game window opens, the loading icon is displayed, but the game crashes right before the intro videos show. I tried using the "-skip_intro" launch option as well, but it didn't change anything.

I tried removing everything from the mods folder except base, BeardLib and BeardLib-Editor, but that didn't help. I tried older versions of BreardLib-Editor, but that didn't help either. I tried using the old deprecated BLT4L, that didn't work.

I've tried everything I think I can do.

**Comment by ontrigger** [comment]
It seems like the game crashes due to the linux version missing DB:create_entry and the editor cannot function without it AT ALL. There is no way to resolve it other than to pray ovk adds it back to the linux version. Close this now

**Comment by Luffyyy** [comment]
Due to Overkill being very half-assed on the Linux port, there are missing functions that will not let neither the editor or custom maps to function.
