### ISSUE TITLE
Unable to download beardlib Editor ("marked as virus")

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#231]
Attempted to download current and older versions, Chrome and Microsoft Edge marks it as a virus and deletes them.

**Comment by Luffyyy** [comment]
Doesn't actually happen for me / I have no idea why both of those shit browsers do that / Try Firefox.

**Comment by Luffyyy** [comment]
It might be a false positive by windows defender https://www.virustotal.com/#/file/444c5994a1e99635aac7a41f2a311b40a44ced9991eb3a98c56510788d5dc463/detection which happens to other popular programs. But again, like me, they have no way to control this. Disable the protection if you can.
