### ISSUE TITLE
Navmesh generation makes the heist crash when I press F10 or try to play.

### ISSUE THREAD

**Issue by vxfmatt** [simon-wh/PAYDAY-2-BeardLib-Editor#232]
Hi, I've been trying to make a map for Payday 2 and everything has been going well. But I tried to create a nav-mesh, and my game crashed at the point the players would spawn no matter what I tried. And then I tried some other things, like changing group states, etc. But it got worse, it crashed whenever I pressed F10.  Then, I did a bit of experimenting. In the start up level with the single floor, spawn, and navsurface, the navmesh works fine. I deleted the nav-surface and added an identical one at the exact same position and deleted the old one. As you can guess, this navmesh crashed my game. This leads me to believe that the problem here is with the editor itself.﻿ I could be wrong, though. I'm just putting it out there.

**Comment by ontrigger** [comment]
send project files

**Comment by vxfmatt** [comment]
like the file in "Maps"? ok
[The Sky Bank.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/2203365/The.Sky.Bank.zip)

**Comment by vxfmatt** [comment]
wait thats not the right one
[The Sky Bank.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/2203385/The.Sky.Bank.zip)
here is the right one, with the built navmesh

**Comment by ontrigger** [comment]
Hmm, interesting. For now the workaround is to reload the map every time you build the navdata

**Comment by vxfmatt** [comment]
thank you! ;)
