### ISSUE TITLE
Custom instances don't sync with clients when placed with InstancePoint Elements.

### ISSUE THREAD

**Issue by Booo3** [simon-wh/PAYDAY-2-BeardLib-Editor#233]
![20180720125704_1](https://user-images.githubusercontent.com/33006056/43036272-7f2a02de-8cfe-11e8-9587-ede3f372c445.jpg)
Haven't tested it with normal instances.

**Comment by ontrigger** [comment]
Make sure the instance has the mission placed button checked

**Comment by Booo3** [comment]
@ontrigger sorry for the late answer, but it should be mission placed. 

For safety u can take a look here. https://drive.google.com/drive/folders/1O60n2XiChMND_rfWGkzY1j_uSHZ5WaYE?usp=sharing

**Comment by ontrigger** [comment]
For now the workaround is to not use mission placed elements

**Comment by Luffyyy** [comment]
While testing my own custom instance the instance showed up in both pcs. I suspect there's something wrong with your setup.

**Comment by Luffyyy** [comment]
Issue is a game bug that will be fixed by BeardLib in the next update.
