### ISSUE TITLE
Element StopwatchOperator crashes

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#236]
Attempting to use the StopwatchOperator element crashes.

Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/Map/MissionScriptEditor.lua:337: attempt to call method 'Value' (a nil value)

SCRIPT STACK

set_element_data() @mods/BeardLib-Editor/Classes/Map/MissionScriptEditor.lua:351
set_element_data() @mods/BeardLib-Editor/Classes/Map/Elements/stopwatchelement.lua:39
_build_panel() @mods/BeardLib-Editor/Classes/Map/Elements/stopwatchelement.lua:87
work() @mods/BeardLib-Editor/Classes/Map/MissionScriptEditor.lua:39
set_element() @mods/BeardLib-Editor/Classes/Map/MissionEditor.lua:76
set_selected_unit() @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:744
add_element() @mods/BeardLib-Editor/Classes/Map/MissionEditor.lua:106
add_element() @mods/BeardLib-Editor/Classes/MapEditor.lua:461
mouse_pressed() @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:624
mouse_press() @mods/BeardLib-Editor/Classes/MapEditor.lua:200
mouse_press() 416
lib/managers/mousepointermanager.lua:339

**Comment by ontrigger** [comment]
Cannot replicate

**Comment by Luffyyy** [comment]
Same, it seems to work fine. Setting, pausing, starting, etc.
