### ISSUE TITLE
Suggestion: Include a "Make Instance" option for levels in a project.

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#238]
Ok here's the logic to it so you can freely edit an instance level without having to move files around.
Reminder, Instances are literally worlds spawned in a world.

-Make a new level in your project (I suggest using "inst_levelname" to keep things clear.)
-In your Main.xml add this anywhere inside the main <table>:

	<instance id="inst_levelname">
		<add directory="assets"/>
		<include directory="levels/inst_levelname">
			<file file="world/world.continent" type="custom_xml"/>
			<file file="world/world.mission" type="generic_xml"/>
		</include>
		<packages/>
		<script_data_mods directory="scriptdata"/>
	</instance>

**Comment by Luffyyy** [comment]
Suggestions moved to https://feathub.com/simon-wh/PAYDAY-2-BeardLib-Editor
