### ISSUE TITLE
Preview Images Cause Crashes

### ISSUE THREAD

**Issue by vxfmatt** [simon-wh/PAYDAY-2-BeardLib-Editor#240]
I went into the main.xml of my custom heist and added an icon.
![image](https://user-images.githubusercontent.com/27796177/43173540-334bdb6c-8f6a-11e8-9688-a2ccdf025ece.png)
![image](https://user-images.githubusercontent.com/27796177/43173541-3611039a-8f6a-11e8-9f1f-f7caab16a8a5.png)
The game crashes on the first loading screen about a split second from startup. Is there a problem with the editor or is this my fault?

**Comment by ontrigger** [comment]
send project files

**Comment by Luffyyy** [comment]
1. Always post a crashlog when you crash.
2. Are you sure your texture is a valid DDS file? That the game accepts? Like try putting overriding a texture in mod overrides.

**Comment by vxfmatt** [comment]
1. Here u go [The Sky Bank.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/2233414/The.Sky.Bank.zip)

2. I don't know where to find crashlogs, and I don't know how to override a texture in mod overrides.

**Comment by ontrigger** [comment]
This is because your texture is corrupted. Here's the crashlog:
`(@IDbf7585933639b68d@, @IDbf7585933639b68d@)Has an unrecognized DDS file type.`
Even photoshop can't open it

**Comment by vxfmatt** [comment]
OHHHH IM SO STUPID

**Comment by RexTheWho** [comment]
Image opens in GIMP just fine, it Lacks an Alpha channel. Without an Alpha channel it will crash.

**Comment by ontrigger** [comment]
please close this then
