### ISSUE TITLE
InstanceParams Element is missing

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#241]
Found in the shared/obj_link instance.

**Comment by Luffyyy** [comment]
Not sure if overkill themselves use it considering it doesn't exactly have editing tools in code.

**Comment by RexTheWho** [comment]
Overkill have used it, only for an obj_link instance and the holdout hostage instance. Its very likely that they hand write it tho.

**Comment by Luffyyy** [comment]
Lucky I found its editor in raid, hoping it will fit.
