### ISSUE TITLE
Removing an Instance from InstanceSetParams element.

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#242]
When changing the selected instance from an instance to "none" crashes.

---

Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/Map/Elements/coreinstance.lua:144: attempt to index a boolean value

SCRIPT STACK

clbk() @mods/BeardLib-Editor/Classes/Map/Elements/coreinstance.lua:221
RunCallback() 485
SetValue() 475
SetValue() 77
SetSelectedItem() 105
ContextMenuCallback() 59
MousePressed() 220
mouse_press() 401
lib/managers/mousepointermanager.lua:339

**Comment by ontrigger** [comment]
Cannot replicate. Need more info.

**Comment by RexTheWho** [comment]
Unable to replicate anymore, closing. If the issue happens again Ill open this up again.
