### ISSUE TITLE
Nav mesh is not getting saved.

### ISSUE THREAD

**Issue by Booo3** [simon-wh/PAYDAY-2-BeardLib-Editor#245]
https://www.youtube.com/watch?v=EkybFtuEA7g

**Comment by Booo3** [comment]
@ontrigger The problem is still present after the fix.

**Comment by ontrigger** [comment]
If the proposed fix did not work then you are having issues with the navmesh generating rather than saving as this fix worked both for me and some other mws discord user. Try deleting a few navmeshes i guess?

**Comment by Booo3** [comment]
@ontrigger Ok after i cleaned the editor and completely reinstallend it, its now working, but still i would like that the restart after the nav generation is optional and not forced. Like it was before.

**Comment by ontrigger** [comment]
@Booo3 restarting is a must because if you go into the playtest mode, the game will crash even if you didn't save the navmesh
