### ISSUE TITLE
elementnavobstacle causing access violations

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#250]
this door_blocker 
![20180814042812_1](https://user-images.githubusercontent.com/33162051/44117407-0d74b116-9fc8-11e8-9760-58e78b919ca7.jpg) causes the game to crash with an access violation if you try to playtest (or play) the heist at all.

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     zip_get_name
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     zip_get_name
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
         payday2_win32_release  (???)     ???
                      KERNEL32  (???)     BaseThreadInitThunk
                         ntdll  (???)     RtlInitializeExceptionChain
         payday2_win32_release  (???)     zip_get_name
                           ???  (???)     ???

-------------------------------

Current thread: Main
Script stack:
                 on_executed()  lib/managers/mission/elementnavobstacle.lua:52
         execute_on_executed()  core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed()  core/lib/managers/mission/coremissionscriptelement.lua:147
                 on_executed()  core/lib/managers/mission/coremissionscriptelement.lua:131
                           f()  lib/managers/mission/missionscriptelement.lua:18
                      update()  core/lib/utils/coreevent.lua:158
                      update()  core/lib/managers/mission/coremissionmanager.lua:529
                      update()  core/lib/managers/mission/coremissionmanager.lua:160
                                core/lib/setups/coresetup.lua:503

-------------------------------

deleting the unit or removing it from the navobstacle elements stops the game from crashing on attempts to playtest/play it.

**Comment by Whurrhurr** [comment]
oh i guess i should clarify: it's added to two navobstacle elements: one to add it as an obstacle, and one to remove it as an obstacle. (when the vault doors open)

**Comment by Whurrhurr** [comment]
found out what the problem was. i switched it to "editor_only" continent and now it works just fine. i blame diesel engine for everything.

**Comment by ontrigger** [comment]
if it crashes, it's an editor related issue that needs fixing

**Comment by ontrigger** [comment]
Not getting any crashes after fixing #258, so I'll close this until further notice @Whurrhurr
