### ISSUE TITLE
Included environments list remains empty after including an environment to the list.

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#251]
![20180814203839_1](https://user-images.githubusercontent.com/33162051/44130374-0783fce6-a002-11e8-81c3-cdb44fee06a0.jpg)
environment is "saved" but not included after clicking on "Include current".

**Comment by Whurrhurr** [comment]
upon further inspection it appears that the environment you select with "include current" is not added to the main.xml file.

**Comment by Luffyyy** [comment]
Issue may have been fixed before but it seems to save to xml just fine.
