### ISSUE TITLE
Continent view toggle issue

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#253]
When toggling visibility of a continent will toggle editor_only to visible if they start hidden.
You can avoid this issue currently by enabling the "Editor Only" option.

**Comment by ontrigger** [comment]
I have no idea what you mean by this

**Comment by RexTheWho** [comment]
Basically if I have Editor units hidden in the settings and then I go to the continents panel and click the eye that makes the continent that contains the editor units hidden they toggle to visible

**Comment by RexTheWho** [comment]
Video example: https://puu.sh/BpQbf/922c97e1d4.mp4

**Comment by ontrigger** [comment]
But... that's intended behavior? All that the editor units button does is toggle units that are only enabled or only exist in the editor. The continent visibility thing only toggles units inside a continent. If you disable the editor units then it would be logical that pressing the continent viewtoggle button would toggle them back on
