### ISSUE TITLE
Creating new project doesnt include certain options

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#254]
When creating new projects important info like contractor is missing.
Default is set to "custom"

**Comment by ontrigger** [comment]
What do you mean the contractor's missing? You can set it right there
![20180821011131_1](https://user-images.githubusercontent.com/8556074/44369488-3d6cc180-a4df-11e8-9c14-f6c1aedac9bb.jpg)

**Comment by RexTheWho** [comment]
Note: This was after opening and saving the level.
