### ISSUE TITLE
Area Triggers "on_enter" option fails with "enemies"

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#256]
Ingame you cannot get an area trigger to execute when an enemy on_enter's the area trigger.

**Comment by ontrigger** [comment]
Uhh, are you sure? Because on ovk maps it seems to work and there is no difference between the serialized data of our editor and ovk's implementation

**Comment by RexTheWho** [comment]
Ive tested over multiple maps, using on_enter doesnt count enemies but when I use while_inside it works fine.

**Comment by ontrigger** [comment]
weird. try seeing if unmodified triggers work on ovk maps maybe? I'll look into this a bit later

**Comment by RexTheWho** [comment]
Ive tested ripping overkills area_triggers from their maps with prefabs, copying from the mission and just spawning a default area_trigger.

**Comment by ontrigger** [comment]
huh, weird. will look into it when I have time

**Comment by Luffyyy** [comment]
Tested and seems to work just fine. If it happens again give me a map to test it in.
