### ISSUE TITLE
Lighting options not working

### ISSUE THREAD

**Issue by GHBDougley** [simon-wh/PAYDAY-2-BeardLib-Editor#259]
I can't find any solutions to this issue, so I'm opening an issue since I can't possibly be the only one experiencing this.

Ingame, lighting options (such as color, type, ranges, etc.) are not present.  I can't find any way to get them to show up, and countless configurations have yielded no results.

Is there anything necessary to get lighting options to appear, or is this potentially an issue?

**Comment by ontrigger** [comment]
you need to extract light units and other dumb stuff into your assets/extract folder for it to work
