### ISSUE TITLE
Can't Move Objets or Select Elements

### ISSUE THREAD

**Issue by Maifummy** [simon-wh/PAYDAY-2-BeardLib-Editor#26]
I have Beardlib, Beardlib Editor, and the phsyics fix mod, but I still can't move objects or select elements. I've tried the different versions of Beardlib (master, dev, modworkshop), I've tried the different versions of the editor (same as Beardlib), and I've tried reinstalling the fix. Another issue is that whenever I uninstall, and reinstall the fix, my game crashes. The only way to fix it is if I verify integrity of game files. Even when I verify integrity of game files, the issue isn't fixed. I'm honestly out of ideas on how to fix it.

**Comment by Luffyyy** [comment]
I seriously don't know, there isn't any way of fixing it other than that, verify files and install the fix it has to work.

**Comment by Maifummy** [comment]
I fixed the issue, in a strange way? I installed two physic fixes at the same time in Bundle Modder, and then uninstalled one of them. After that, it worked perfectly fine.

**Comment by Luffyyy** [comment]
Whatever floats your boat, uninstall it before updates.
