### ISSUE TITLE
I don't see the utilities window.

### ISSUE THREAD

**Issue by Enzinu** [simon-wh/PAYDAY-2-BeardLib-Editor#260]
I don't have the Utilities, why this appening? Help me please!﻿
in the log appear thats:
 (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function node_from_xml_vr
(c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function try_open_base_vr (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function luaL_newstate_vr

**Comment by ontrigger** [comment]
you need to have both beardlib and beardlib editor along with superblt to get the utilities button. This repo is for reporting bugs related to the editor, for an installation guide refer to the readme
