### ISSUE TITLE
Fog "max density" slider does nothing

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#262]
a recent update to the editor made it so that the "Max density" slider for fog in the environment settings does nothing.
![20180902192345_1](https://user-images.githubusercontent.com/33162051/44964540-f2db4400-aee5-11e8-8afd-66786f4ff12e.jpg)
here we see max density is set to 1.000 (or 100%) but in the next image 
![20180902192349_1](https://user-images.githubusercontent.com/33162051/44964553-02f32380-aee6-11e8-8c49-f14f0c277ccb.jpg) max density is set to 0.000 (0%) but the fog density itself has not changed.

**Comment by ontrigger** [comment]
weird, seems to work fine on my end

**Comment by Whurrhurr** [comment]
real late response but if you load a PAYDAY: The Heist environment you're locked out of being able to set the max density on fog. something in PD:TH's .environment files is different from PD2's .environment files for fog densities.

**Comment by ontrigger** [comment]
There is no code in ovk editor to modify density for pdth env files, the only reason it works is backwards compatibilty
