### ISSUE TITLE
Zeal taser missing from the spawnenemydummy units list

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#265]
when looking for a unit to select for a spawnenemydummy element, "units/pd2_dlc_gitgud/characters/ene_zeal_tazer/ene_zeal_tazer" does not show up on the list. even looked at it in enemy spawner and if you browse units it's not there.

**Comment by Luffyyy** [comment]
Fixed a while ago when updating the hashlist I assume
