### ISSUE TITLE
[Extract Loading] Some units will include duplicate loads in add.xml

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#278]
Some units like Safes and Armored Transport Vehicles will include duplicates of the same assets in the add.xml, sometimes including 5 of the same unit in the list.

My guess for this is the editor just grabs whatever's paths are shown on the assets but no cleanup afterwards to remove duplicates.

I suspect this may cause longer loading times since if you load the 8 main safes you have over 40 duplicate assets listed per safe.

**Comment by Luffyyy** [comment]
If you mean there are the same assets for each that is loaded then it should be fine, it checks if these files are loaded so it won't load if it's loaded already. The editor uses these to know if to completely remove the asset.

**Comment by RexTheWho** [comment]
Not the issue, The issue is if I were to load a 1x1m titan safe you would see multiple of the same assets listed in the 1x1m safe add.xml (eg. gold bar .unit pickup being listed twice or more)

Afaik it causes no issues with loading or unloading.
