### ISSUE TITLE
Editing menu for light_omni doesn't appear

### ISSUE THREAD

**Issue by Quackertree** [simon-wh/PAYDAY-2-BeardLib-Editor#28]
Hi there!

I've, since practically always, been editing light_omni by hand via the file, because I thought you couldn't edit that in-editor. Suddenly, someone tells you can - I go check it out, but apparantly the menu doesn't appear on my side?

I selected a light_omni, look in the left-side menu & then there's nothing except the standard "Transform" tag. Anything I'm missing here?

Naturally, I'm using the latest version of BeardLib.

Here's proof that it ain't working for me (afaik): ![Proof](https://user-images.githubusercontent.com/19995547/29486622-e0394c32-84ea-11e7-8bbe-61a67623849e.jpg)

**Comment by Luffyyy** [comment]
Do you have extracted files?

**Comment by Quackertree** [comment]
As in extracted files from the PD2BundleModder? Yes, I do. - It's not in the default directory, though. I've put them somewhere in My Documents. Do they need to be in a specific place?

**Comment by Luffyyy** [comment]
Set the directory in the options to yours
make sure it contains forward slashes and not backslashes.
