### ISSUE TITLE
I need help to download

### ISSUE THREAD

**Issue by iTom33ro** [simon-wh/PAYDAY-2-BeardLib-Editor#283]
hello Simon, i need help to download this editor, in dry to download but i need a _.pdmod_ to download. You can help me?

**Comment by Luffyyy** [comment]
You don't need the pdmod, just install SuperBLT and the editor should run.

**Comment by iTom33ro** [comment]
Im installing SuperBLT, but now the game give me error (0xc0000142).

**Comment by Luffyyy** [comment]
Make sure you removed any previous DLL (iphp thingy especially)
Install from here: https://superblt.znix.xyz/ I recommend reading the instructions.

**Comment by Luffyyy** [comment]
Anything else please forward to the SBLT dev here: https://gitlab.com/znixian/payday2-superblt

**Comment by iTom33ro** [comment]
i don't have old version of this instruction, this is firs time to install.

**Comment by iTom33ro** [comment]
`07:45:09 PM Log:  (c:\users\znix\source\repos\superblt\src\debug\blt_debug.cpp:124) Command line: "D:\PAYDAY.2.Ultimate.Edition.Incl.ALL.DLCs\PAYDAY.2.Ultimate.Edition.Incl.ALL.DLCs\payday2_win32_release.exe" 
07:45:09 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:27) Could not open signature cache file
07:45:09 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:255) Scanning for signatures in payday2_win32_release.exe
07:45:11 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_call
07:45:13 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_pcall
07:45:14 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_gettop
07:45:15 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_settop
07:45:18 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_toboolean
07:45:22 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_tointeger
07:45:25 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_tonumber
07:45:28 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_tolstring
07:45:29 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_objlen
07:45:31 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_touserdata
07:45:33 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function luaL_loadfilex
07:45:34 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function luaL_loadstring
07:45:35 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_getfield
07:45:37 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_setfield
07:45:39 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_createtable
07:45:42 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_newuserdata
07:45:43 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_insert
07:45:45 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_remove
07:45:48 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_newstate
07:45:50 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_close
07:45:54 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_settable
07:45:57 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_setmetatable
07:46:00 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_getmetatable
07:46:02 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_pushnumber
07:46:04 PM WARNING:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:210) Failed to locate function lua_pushinteger`
