### ISSUE TITLE
[UI] Light unit options missing

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#284]
Latest version, lighting options missing on some light units
![image](https://user-images.githubusercontent.com/26837908/47951054-72dd6300-df96-11e8-93b5-d4d08c7ceebc.png)

**Comment by Nepgearsy** [comment]
that's not normal. you have the extract folder set correctly?

**Comment by ontrigger** [comment]
You need to extract this file in order to use it
