### ISSUE TITLE
Map crashes when loading it without the editor enabled.

### ISSUE THREAD

**Issue by Booo3** [simon-wh/PAYDAY-2-BeardLib-Editor#287]
https://drive.google.com/file/d/1-3pxeycYivRmYSfjaeDSa3hedGKm63Q2/view?usp=sharing

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
        _create_statics_unit()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:453  
                      create()  core/lib/utils/dev/editor/coreworlddefinition.lua:522  
                      create()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:31  
                create_world()  core/lib/utils/dev/editor/worldholder.lua:110       
                   init_game()  lib/setups/gamesetup.lua:645                        
                                core/lib/setups/coresetup.lua:405                   

-------------------------------

System information:
	Application version : 1.92.760
	CPU : AMD Ryzen 5 1600 Six-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[25.21.14.1616]
	Language : english
	Memory :     8126MB 964KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (VoiceMeeter Input (VB-Audio VoiceMeeter VAIO))

**Comment by Booo3** [comment]
The map:
https://drive.google.com/drive/folders/1c1wKDArdftf50gKfQltntXTCpN5GWYfn?usp=sharing

**Comment by Booo3** [comment]
@ontrigger should i post this issue in the Beard lib git?

**Comment by ontrigger** [comment]
I'll take a better look at it and decide myself

**Comment by Luffyyy** [comment]
"units/payday2/props/com_prop_vent_ceiling/com_prop_vent_ceiling" -> physic_effects/push_sphere.physic_effect.xml, removing the .xml solves the issue. No idea why such a specific unit is not always loaded but it's just 1kb so shouldn't matter as much, check your extract to make sure it has no ".xml".

The real issue however, seems to be that the editor packages are loading "core/units/run_sequence_dummy/run_sequence_dummy" while outside the editor these won't work. The best solution would be adding that unit to beardlib itself as it's really simple and is a few bytes. Again, a unit that should've been always loaded but overkill.

**Comment by Luffyyy** [comment]
The BeardLib version should be out today or tomorrow; hopefully.
