### ISSUE TITLE
Environment Editor - Frustrating to Use?

### ISSUE THREAD

**Issue by GHBDougley** [simon-wh/PAYDAY-2-BeardLib-Editor#29]
This is more of a personal issue, but compared to older versions of the editor, the environment editor is much more frustrating to use.

I'd like to see it partially return to the old system, where you can edit it from anywhere inside or outside of editor mode (when in SP only?), and for it to stop resetting things like the various shadow slice, etc. settings on startup.  Additionally, I'd also like it to support manually typing in values that go past the default limit (the ingame one currently supports up to 10k for shadowslices?  but ovk's envs use easily much more than that, fog values do this as well).

I'd also recommend making whatever panel it uses a very low opacity, or having a button to temporarily hide it while performing edits.  Past that, though, I do quite like the current rendition of it.

**Comment by Luffyyy** [comment]
the new editor is based of the actual editor so no can do, the old one was extremely buggy and had many missing features.

I'll see if it reset the values and comment here again about it.
I can always increase any values if it's needed.
I already planned to add something to hide the editor screens

**Comment by GHBDougley** [comment]
Currently, I've been messing around with the shadows, and it seems there's a lot of oddities with how each value behaves, and there should be different max/min limits..?  I need to test more to see what these could possibly be.

Also, ambient scale appears to be non-functional in editor.

**Comment by Luffyyy** [comment]
Not really sure what you mean by that but I'd prefer you to open a new issue for that
