### ISSUE TITLE
Cannot build cubelights with light_omni_shadow_projection_01_seq units

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#290]
title. trying to build cubemaps with light_omni_shadow_projection_01_seq units causes them to be skipped over, or if they're the only selected units then nothing happens at all. the only way to build cubemaps with them is to change them to light_omni_shadow_projection_01, select them, and then build cubemaps and reload the level without saving the unit changes.

**Comment by ontrigger** [comment]
You need to have that unit in your extract folder for it to work. It will also magically get the ability to be edited
