### ISSUE TITLE
Editor units will show up if "Editor Units" is ticked off if they're part of a(n) portal(s)

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#294]
![218620_20181206101356_1](https://user-images.githubusercontent.com/33162051/49641684-c09a2080-f9c5-11e8-9e53-a00d188af35b.png)

**Comment by ontrigger** [comment]
Why would you put them there? I think the editor forces to draw them or something maybe not actually i have no idea i haven't looked into the code this is not an issue and once again you should never put them in a portal bye
