### ISSUE TITLE
Clicking "cancel" on continent settings crash the game

### ISSUE THREAD

**Issue by mwSora** [simon-wh/PAYDAY-2-BeardLib-Editor#296]
Current thread: Main
Script stack:
                   unit_data()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:669  
                        name()  core/lib/managers/coresoundenvironmentmanager.lua:1031  
           loaded_continents()  @mods/BeardLib-Editor/Classes/Map/SoundLayerEditor.lua:21  
           loaded_continents()  @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:26  
             load_continents()  @mods/BeardLib-Editor/Classes/MapEditor.lua:468     
                        clbk()  @mods/BeardLib-Editor/Classes/Dialogs/ContinentSettingsDialog.lua:71  
                 RunCallback()  485                                                 
                MousePressed()  87                                                  
                MousePressed()  162                                                 
                 mouse_press()  416                                                 
                                lib/managers/mousepointermanager.lua:339

**Comment by ontrigger** [comment]
Fixed by luffy some time ago
