### ISSUE TITLE
Clear units button still crash the game

### ISSUE THREAD

**Issue by mwSora** [simon-wh/PAYDAY-2-BeardLib-Editor#298]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                   unit_data()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:669  
                        name()  core/lib/managers/coresoundenvironmentmanager.lua:1031  
           loaded_continents()  @mods/BeardLib-Editor/Classes/Map/SoundLayerEditor.lua:21  
           loaded_continents()  @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:26  
             load_continents()  @mods/BeardLib-Editor/Classes/MapEditor.lua:468     
                                @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:293  
                        clbk()                                                      
                           178  RunCallback()                                       
                                485                                                 
                MousePressed()                                                      
                            87  MousePressed()                                      
                                162                                                 
                 mouse_press()                                                      
                           416  lib/managers/mousepointermanager.lua:339

**Comment by Luffyyy** [comment]
Doing a quick test doesn't seem to crash

**Comment by Luffyyy** [comment]
Anyway open again with project to test with if ever happens again
