### ISSUE TITLE
Unloading assets you have in your add.xml in-game with the "Unload Asset" button also unloads every asset that's below it in add.xml

### ISSUE THREAD

**Issue by Whurrhurr** [simon-wh/PAYDAY-2-BeardLib-Editor#299]
how has no one noticed this? it's really annoying. steps to recreate this are simple: open up your add.xml after you've loaded at least 10 assets (only 4 of those should be placed in the level and the other 6 will go unused) via extract and place 4 assets you loaded via extract, make sure none of the ones you placed are the first asset you loaded from extract, save, reload level and go into Management and tools > Assets, check the first thing in your add.xml for your level (make extra sure that you also don't use your first asset loaded) select the first asset on the list, then select "Unload asset" and select "Yes", now look at your add.xml in what ever text editor you use, it should ask/prompt you to reload the file because it has been altered. selecting yes will show you that that any asset below the asset you've loaded in the xml is now gone. this is a large inconvenience if you have multiple assets loaded from extract and want to unload your unused assets that are loaded from your asset extract folder. you'll unknowingly also unload every asset that's below it in the xml file.

**Comment by ontrigger** [comment]
Beardlib issue, will issue a pull request

**Comment by ontrigger** [comment]
Fixed in latest beardlib
