### ISSUE TITLE
[Suggestion] Add "Copy Unit position" to the "MoveUnit" Element

### ISSUE THREAD

**Issue by Babyforce** [simon-wh/PAYDAY-2-BeardLib-Editor#30]
Hello, I have started to use the editor few weeks ago and was playing with the MoveUnit Element and noticed that there was no option to copy the position of a unit on the map to the "Translate End Position" of the element. This is why I would like to ask if you could add such an option to this element so it is easier to move objects to a precise point.

Thanks for taking this in consideration.

**Comment by Luffyyy** [comment]
Added, forgot to close
