### ISSUE TITLE
Crashes when trying to spawn instances

### ISSUE THREAD

**Issue by Ardaboo766** [simon-wh/PAYDAY-2-BeardLib-Editor#301]
Whenever I try to add an animated unit or an instance, the map crashes. Supermod, safe mode, physics fix, nothing helped. You have to do something

**Comment by ontrigger** [comment]
No crashlog, no info on what units youre adding and how you're doing it. I can't fix it if you don't cooperate

**Comment by Ardaboo766** [comment]
All instances, plus all anim vehicles. 
[2019_02_03_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/2825660/2019_02_03_log.txt)
You notice the "curl closed" in the end?

**Comment by ontrigger** [comment]
That's not the right log. The actual crash.txt file is located at Users/%USERNAME%/AppData/Local/PAYDAY 2

**Comment by ontrigger** [comment]
Weird, this seems to be an issue on your end. Try deleting the editor and then installing from this repo instead. Also try installing the latest version of superblt

**Comment by Ardaboo766** [comment]
Superblt crashes my game, and this IS the latest repo

**Comment by Ardaboo766** [comment]
I downloaded from you

**Comment by ontrigger** [comment]
you need the latest version of superblt for the editor to work properly or at all

**Comment by Ardaboo766** [comment]
Superblt crashes my game

**Comment by ontrigger** [comment]
The editor will not work properly without superblt. You'll need to resolve the issue with it for the editor to work.
