### ISSUE TITLE
Custom Instances crash on selection

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#303]
When selecting an instance added in the main.xml like this will crash.
You can still place them and activate them ingame but any selection to them in the editor is impossible.

```
    <instance id="inst_levelname">
        <add file="levels/inst_levelname/add.xml"/>
        <include directory="levels/inst_levelname">
            <file file="world/world.continent" type="custom_xml"/>
            <file file="world/world.mission" type="generic_xml"/>
        </include>
        <packages/>
        <script_data_mods directory="scriptdata"/>
    </instance>
```

```
Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/Map/InstancesEditor.lua:139: attempt to index field 'default' (a nil value)



SCRIPT STACK

update() @mods/BeardLib-Editor/Classes/Map/InstancesEditor.lua:112
update() @mods/BeardLib-Editor/Classes/MapEditor.lua:596
func() @mods/BeardLib-Editor/Core.lua:317
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:260
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540
```

**Comment by MiamiCenterPL** [comment]
I had the same crash before, I think you have to change the script of the world.mission thing, if you have for example "<entry key="script" type="string" value="custom"/>" it will crash, changing that to "<entry key="script" type="string" value="default"/>" should fix issue, atleast it does for my Instance :v

**Comment by RexTheWho** [comment]
Not sure what you mean by all that. In the world.mission the only bit of instance data Im aware of is at the bottom and value means the instances name.
There is a line below it
<entry key="name" type="string" value="default"/>
But its already what you suggested.

**Comment by RexTheWho** [comment]
Messed around a bit and I think this is an issue if you remake the world mission/continent.
Deleting the world continent and then making a new one may cause this issue.

**Comment by MiamiCenterPL** [comment]
For me that happened when I had more Continents in instance, bcs I think it's working only with "world" in continent and "default" in mission.

**Comment by ontrigger** [comment]
Would really like you guys to send me a map that crashes

**Comment by RexTheWho** [comment]
https://puu.sh/D2IrM/82d5f098c5.zip

Here's my project:
inst_vault is the trouble instance.
inst_ammo is a working instance.

**Comment by ontrigger** [comment]
Added a check to prevent making custom named missionscripts for the world continent
