### ISSUE TITLE
Pasting unit translation fails

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#307]
Attempting to Copy and then Past translation coordinates in editor shows while holding it down but does not apply to the unit.

Video: https://puu.sh/D58CL/37d9a86fb3.mp4

**Comment by Luffyyy** [comment]
Fixed in https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/commit/b5d58da40cc9b3184a24a99a468a9efc6949227f
