### ISSUE TITLE
BeardLib Editor Crashing with Anything

### ISSUE THREAD

**Issue by justalemon** [simon-wh/PAYDAY-2-BeardLib-Editor#37]
So, i installed BeardLib, BeardLib-Editor and the PDMOD on the readme but the game is crashing doing anything other than navigating the menus. There's no other mods installed.

BLT version 2.1
PAYDAY 2 version 2090578 aka 155.1

The crash files:

[payday2_win32_release_2117156_crash_2017_9_5T20_14_59C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278916/payday2_win32_release_2117156_crash_2017_9_5T20_14_59C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_18_34C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278918/payday2_win32_release_2117156_crash_2017_9_5T20_18_34C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_24_47C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278919/payday2_win32_release_2117156_crash_2017_9_5T20_24_47C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_27_58C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278920/payday2_win32_release_2117156_crash_2017_9_5T20_27_58C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_46_39C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278917/payday2_win32_release_2117156_crash_2017_9_5T20_46_39C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_47_14C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278923/payday2_win32_release_2117156_crash_2017_9_5T20_47_14C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_56_32C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278922/payday2_win32_release_2117156_crash_2017_9_5T20_56_32C0.zip)
[payday2_win32_release_2117156_crash_2017_9_5T20_58_25C0.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1278921/payday2_win32_release_2117156_crash_2017_9_5T20_58_25C0.zip)

**Comment by Luffyyy** [comment]
BeardLib's latest version is **2.35** that's not the crash log also.

**Comment by justalemon** [comment]
Ah shit, i posted the BLT version, and that's the .mdmp for debugging.

**Comment by justalemon** [comment]
Also looks like the ModWorkshop versions are the problem, if i download the repos directly from GitHub (both BeardLib and BeardLib-Editor) the game runs fine.
