### ISSUE TITLE
unable to find where to open the editor

### ISSUE THREAD

**Issue by Toopixelated** [simon-wh/PAYDAY-2-BeardLib-Editor#38]
as of updating to blt 2.0 and updateing both beardlib and the editor i can not the the button in the options to open the editor where is the new location as i can not find out

![041036e9e48d7db3e3f321a2be926454](https://user-images.githubusercontent.com/31697495/30114316-6a640ffa-930f-11e7-9c58-858e10357eec.png)

**Comment by Luffyyy** [comment]
what version do you have for both editor and beardlib?

**Comment by Toopixelated** [comment]
![0e6beb272de212ff6622f1f7a1c0bdb7](https://user-images.githubusercontent.com/31697495/30114541-09035558-9310-11e7-84d4-7e9e5b041c3c.png)
![0b067eb6674ae3ae507d420e7e7aac7a](https://user-images.githubusercontent.com/31697495/30114542-0aea30da-9310-11e7-8fea-c368afa142e2.png)

**Comment by Luffyyy** [comment]
(for beardlib and beardlib mods you should use the beardlib mods manager I'm just too lazy to update the version for that menu also everytime)
But yeah I need your log file, something is probably preventing it from being created.

**Comment by Toopixelated** [comment]
im sorry what logs am i sending you? 
the mini dump crash logs?

**Comment by Toopixelated** [comment]
[2017_09_06_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1281302/2017_09_06_log.txt)

i think this is what you wanted

**Comment by Luffyyy** [comment]
02:51:18 PM Lua: [ERROR][BeardLibEditor] BeardLib is not installed!
Try reinstalling BeardLib

**Comment by Toopixelated** [comment]
yea i have reinstalled multiple times and the same error is comming up in the log im going to try to redownload the whole game and reinstall all mods
