### ISSUE TITLE
Opening heist through beardlib editor menu doesn't load into editor

### ISSUE THREAD

**Issue by BobTheBob9** [simon-wh/PAYDAY-2-BeardLib-Editor#39]
When I open a heist in the beardlib menu, it just doesn't load it into the editor, I get no grey loading box like this https://image.prntscr.com/image/yiB2He7fRRm5ougaH5-onw.png, either. F10 does nothing, even on OVERKILL heists (e.g. nightclub)
Here's a conversation I had with Quackertree about this issue: ![beardlib editor error1](https://user-images.githubusercontent.com/32057864/30593178-a7f553ec-9d41-11e7-9779-ce5c79450986.PNG)

**Comment by Luffyyy** [comment]
F10 only works in editor mode, are you sure you're loading the heists through the BeardLib-Editor menu - levels? 
What version are you on?

**Comment by BobTheBob9** [comment]
I'm on the newest version of beardlib and beardlib-editor, I have been loading heist through BeardLib-Editor menu - levels

**Comment by Luffyyy** [comment]
Give me your log file

**Comment by BobTheBob9** [comment]
If you mean a crash log, I don't have one as my game didn't crash at all

**Comment by Luffyyy** [comment]
mods/logs.

**Comment by BobTheBob9** [comment]
[logs.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1317782/logs.zip)

**Comment by Luffyyy** [comment]
07:41:39 AM FATAL ERROR:  (..\src\InitiateState.cpp:388) cannot open EnvironmentManager.lua: No such file or directory
There's something wrong with your BeardLib I assume, delete it completely and install it from here https://modworkshop.net/mydownloads.php?action=view_down&did=14924

**Comment by BobTheBob9** [comment]
Still have the same issue, here's my current logs now
[logs.zip](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1317828/logs.zip)

**Comment by BobTheBob9** [comment]
Also after checking my beardlib and beardlib-editor hooks folder, enviromentmanager.lua is in both of them

**Comment by Luffyyy** [comment]
02:07:48 PM FATAL ERROR:  (..\src\InitiateState.cpp:408) mods/BeardLib/Hooks/MenuComponentManager.lua:42: attempt to index global 'BLTNotificationsGui' (a nil value)
Please update your BLT.

**Comment by Luffyyy** [comment]
In anyway what's wrong is not the editor it's most likely the version of BLT you have which is outdated.
