### ISSUE TITLE
[crash] beardlib editor menu seems to work fine, loading into heists doesnt work though

### ISSUE THREAD

**Issue by brunaiki** [simon-wh/PAYDAY-2-BeardLib-Editor#40]
heyo ive read the other crashs and issues but mine seems to be slightly different but close.
i can use the beardlib editor menus to create new projects/ levels/ clone leves/ change values etc etc etc. but as soon as i try to load a level to edit it with the editor the game crashes. it shows the black loading screen with the spinning loading icon for about 5 seconds. then the loading icon freezes and the game crashes.
- im running the latest version of beardlib from the mod workshop (just downloaded it right now)
- i also have the latest dev version of the editor installed (from github - just downloaded that as well)
- i am also using the latest beardlib physics editor pdmod file from the dropbox (just downloaded it)

anything you can think of at the moment? :)
my crash file sadly always shows this:

Application has crashed: unknown exception

-------------------------------

Callstack:

                    KERNELBASE  (???)     RaiseException                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.332.
	CPU : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 960 / nvd3dum.dll[22.21.13.8205]
	Language : english
	Memory :     12240MB 516KB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : VB-Audio Software (VoiceMeeter Input (VB-Audio VoiceMeeter VAIO))

**Comment by Luffyyy** [comment]
How hard it is to look at dates? master is clearly the latest.
"i also have the latest dev version of the editor installed (from github - just downloaded that as well)"

**Comment by brunaiki** [comment]
oh yeah lol ^^ my bad... I mixed that one up. I will try it out and let you know :) thansk for the quick response

**Comment by brunaiki** [comment]
hm still the same error :(
deleted old beardlib editor, downloaded new one and added that to my mods folder. menu works fine, same crash when trying to load into levels

Application has crashed: unknown exception

-------------------------------

Callstack:

                    KERNELBASE  (???)     RaiseException                                      
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???

**Comment by Luffyyy** [comment]
send me blt log.

**Comment by brunaiki** [comment]
[2017_09_20_log.txt](https://github.com/simon-wh/PAYDAY-2-BeardLib-Editor/files/1317792/2017_09_20_log.txt)

**Comment by Luffyyy** [comment]
Not sure, but it seems like some mods are giving errors, try running the game just BeardLib and the editor.

**Comment by brunaiki** [comment]
okay ill try running it with no other mods :) do you know which mods might cause the problem?

**Comment by Luffyyy** [comment]
No idea you have a few errors there, try toggling one by one.

**Comment by brunaiki** [comment]
works without mods, couldnt figure out which mod caused the problem yet... now i am to stupid to figure out how to move around in the editor ^^* can you give me a hint?

**Comment by brunaiki** [comment]
okay i finally figuered it out. the crash is caused by a mod which adds one liners to the loading screen. editor works fine now. except i still cant figure out how to move lol... i fell like im retarded https://modworkshop.net/mydownloads.php?action=view_down&did=18012

**Comment by Luffyyy** [comment]
Possible mods(first ones have bigger chances to be the cause) 
- [Mallcrasher] Add Loot Secure Point
- 3rd Person Longview Driver Camera
- Blue Bodybag Contour
- ECM Low Battery Fix
- Hotline Miami HUD
- HQ Inventory Icons
- Mod List Light
