### ISSUE TITLE
"Manage Access Flags" menu refusing to close.

### ISSUE THREAD

**Issue by Liarra-Sniffles** [simon-wh/PAYDAY-2-BeardLib-Editor#43]
What it says on the tin.
Issue appeared to start at some point after the menu style update as before then was the last time I tried modifying a special objective's access flags individually. Once opened the access flags menu refuses to close; popping back up an instant after closing.

Problem persists with all other mods removed and fresh install.

**Comment by Luffyyy** [comment]
BeardLib issue, should be resolved next update
