### ISSUE TITLE
Crashing upon opening a level with this and SuperBLT

### ISSUE THREAD

**Issue by BreakinBenny** [simon-wh/PAYDAY-2-BeardLib-Editor#45]
Ever since I moved from the original BLT to SuperBLT, I've been unable to use BeardLib's level editor because of it. First I get to the part where it loads the "cag_vents" for Car Shop for example, and then it crashes to desktop.

Thu Dec 28 20:37:26 2017

Application has crashed: C++ exception
mods/BeardLib-Editor/Hooks/MissionManager.lua:449: attempt to index field 'mission' (a nil value)

SCRIPT STACK

create_element() @mods/BeardLib-Editor/Hooks/MissionManager.lua:423
_create_elements() @mods/BeardLib-Editor/Hooks/MissionManager.lua:404
original() core/lib/managers/mission/coremissionmanager.lua:403
init() @mods/base/req/core/Hooks.lua:185
new() core/lib/utils/coreclass.lua:35
MissionManager_add_script() core/lib/managers/mission/coremissionmanager.lua:113
_add_script() @mods/BeardLib/Hooks/MissionManager.lua:10
_load_mission_file() @mods/BeardLib-Editor/Hooks/MissionManager.lua:90
parse() @mods/BeardLib-Editor/Hooks/MissionManager.lua:42
init_game() lib/setups/gamesetup.lua:640
core/lib/setups/coresetup.lua:402

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.86.496.
	CPU : Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 960 / nvldumd.dll[23.21.13.8871]
	Language : english
	Memory :     8132MB 48KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Högtalare (High Definition Audio Device))

…What to do?

**Comment by Luffyyy** [comment]
fixed in the last update
