### ISSUE TITLE
Moving element issues

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#47]
Moving elements in the world with the XYZ 3D arrows will cause frame drops, very noticeable on larger maps.

Moving many elements (usually with a unit selected) will not properly update the new position causing elements to move back on reload.

**Comment by Luffyyy** [comment]
Latest update should improve this. Sadly I might be reaching the limit of how optimization I can do.

**Comment by RexTheWho** [comment]
Notice, this is still an issue.
![218620_20180228163054_1](https://user-images.githubusercontent.com/26837908/36777595-053f2b76-1ca5-11e8-84a0-ed8d5d427990.png)
