### ISSUE TITLE
Element link issues on delete

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#48]
When deleting an element that is linked to something and then saving elements can link unrelated elements together.

Example 'Element_A' (id 100111) is linked to 'Element_B' (id 100001) and 'Element_C' (id 100002) exists but isn't connected to either A or B.
When Element_B is deleted Element_C gets linked to Element_A.

Repro steps unknown exactly.

**Comment by RexTheWho** [comment]
Additional element link issue:
Example: https://puu.sh/yXjjo/a7f71d208d.rar
Open "wetwork_burn" level,
Select any unit,
Alt + Click 3D arrows to duplicate the unit until you notice some will be connected random elements.

This only seems to happen when you delete a unit that was previously connected to an element, the unit id stays with the element and will connect back up to whatever random unit gets picked to use the old unit id.

**Comment by Luffyyy** [comment]
Please retry on the latest build, I rewrote the linking system.

**Comment by Luffyyy** [comment]
Please report this again if it happens.
