### ISSUE TITLE
unit id numbers causing invisible props

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#49]
Reproduction unknown, but changing id from something like 100000 to 101000 fixes this.
Collisions and interactions are not affected but the prop unit cannot be seen

(Example of a problematic unit)
		<table>
			<unit_data _prev_pos="3970.13 -3777.9 3.72529e-007" _prev_rot="0 0 0 -1" continent="world" local_pos="0 0 0" local_rot="0 0 0 1" name="units/pd2_dlc_dinner/props/din_barrel/din_barrel" name_id="din_barrel_009" position="3970.13 -3777.9 3.72529e-007" rotation="0 0 0 -1" unit_id="100691"/>
		</table>

![image](https://user-images.githubusercontent.com/26837908/34697511-675bd4c6-f50e-11e7-8b35-f72e16afdcf5.png)

**Comment by RexTheWho** [comment]
SOLVED!
This issue is related to Portals, Portals keep ids when the unit that uses said id is deleted.
There seems to be a big row of problems with unit ids recently, I hope this can be fixed soon.

**Comment by Luffyyy** [comment]
Last update added listing of portals
I'm thinking about removing the unit id when it's deleted from portal.
