### ISSUE TITLE
Nothing in BeardLib main menu and no mod options with BeardLib Editor installed

### ISSUE THREAD

**Issue by Thestickman391** [simon-wh/PAYDAY-2-BeardLib-Editor#5]
BeardLib main menu
![Nothing in BeardLib main menu](http://i.imgur.com/MQsoaHK.jpg)
Mod options
![Nothing in mod options](http://i.imgur.com/1rmLn5f.jpg)
Note that I do have mods installed that have options and if I remove BeardLib Editor all the mod options return.
Also on the main menu all of my mod related menu stuff (Fast.net, Safehouse, etc) are also not there.

**Comment by Luffyyy** [comment]
I'd assume you're using the master branch's editor which is unsupported right now and probably broken
so please do not report issues until the dev branch will be in public.

**Comment by Thestickman391** [comment]
The same thing happens with the dev branch though

**Comment by Luffyyy** [comment]
Dev branch doesn't use that menu anymore you'll need to use dev BeardLib as well.
