### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#51]
-Reintroduce "Disabled" element visuals:
Use a shaped icon with a cross in it to show its disabled.

-Show only and/or Select only [name] continent:
eg. have editor_only shown but cannot see the regular world continent.

-Visualise connected elements (up to: [number]):
If element 1 to 9 are linked in order and my visualise connected elements are enabled and set to 6 "element 1" will show its link to element 2 and element 2 will show its link to element 3, and so on until the limit.

-Preview unit animations:
If I have a Special objective, Enemy spawner or Civilian spawner element selected include a debug preview animations section.

-Add "interact" sequence to all unitsequencetriggers:
Currently you have to edit those in the mission_script file to apply them, they also show as blank when you use sequences the editor isnt aware of (Doors often use done_exploded, done_opened as their triggers and are not available on all doors Ive seen)

EDIT:
-Brushes:
I think its possible to finally add a massunit.massunit with SuperBLT but not 100% sure.

-Nav Obstacles:
No clue how they work exactly but they don't seem to work without adding a script and if you rebuild navigation nav obstacles break, says Quackertree long ago.

-Lighting: shadow_projection:
Tested and adding <projection_textures ls_spot="YOUR_TEXTURE_PATH_HERE"/> works but cannot be accessed in the editor menu, a browse textures option might be difficult but allowing people to type in their assets file path should be fine, like enemy/civilian units.

Additionally the code for lightmap gen seems to still be ingame, same goes for the orthographic code, having those would be really useful for map development.

EDIT:
Select all button for unit selection to mass select certain units like loot or editor items
![image](https://user-images.githubusercontent.com/26837908/37561574-7c074122-2a8c-11e8-9092-4911a16c6367.png)

**Comment by Luffyyy** [comment]
Any new suggestions please add as a new issue so I can follow it better.

**Comment by ontrigger** [comment]
You can now hide continents/groups so you can cross off the first two entries from the list

**Comment by Luffyyy** [comment]
Moved to https://feathub.com/simon-wh/PAYDAY-2-BeardLib-Editor
