### ISSUE TITLE
crash.txt

### ISSUE THREAD

**Issue by MiamiCenterPL** [simon-wh/PAYDAY-2-BeardLib-Editor#6]
Application has crashed: C++ exception
[string "lib/utils/game_state_machine/gamestatemachi..."]:601: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.209
	CPU : Intel(R) Pentium(R) CPU 2117U @ 1.80GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics / igdumdim32.dll[10.18.10.4358]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     3985MB 280KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Głośniki (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
More information would appreciated.

**Comment by Luffyyy** [comment]
Again please don't report issues of master branch atm.
If you want to test the dev branch you need to download it + BeardLib dev.
