### ISSUE TITLE
Dropdown sequence issues

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#60]
typing in sequences messes up the dropdown list and you cant select other options.

![image](https://user-images.githubusercontent.com/26837908/36952536-5155eef0-204c-11e8-9367-8f683e5b414a.png)

**Comment by Luffyyy** [comment]
where did you write this? clearly light editor doesn't have such dropdown

**Comment by RexTheWho** [comment]
This was on a Helicopter, some units have lights attached like swat vans, player vans and helicopters.
