### ISSUE TITLE
Loading an instances level crashes

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#62]
Loading an instance level to edit crashes, seems like its because it has no world.world so if some default one was added that instances load with when you edit them might work

Application has crashed: C++ exception
[string "core/lib/utils/dev/editor/worldholder.lua"]:42: levels/mods/instance_level_name/world.world is not in the database!

SCRIPT STACK

init() core/lib/utils/dev/editor/worldholder.lua:42
new() core/lib/utils/coreclass.lua:35
init_game() lib/setups/gamesetup.lua:633
core/lib/setups/coresetup.lua:405

**Comment by Luffyyy** [comment]
how did you even load it?!

**Comment by RexTheWho** [comment]
![image](https://user-images.githubusercontent.com/26837908/37009782-762b350a-2123-11e8-9b58-f30bcee08b0d.png)
![image](https://user-images.githubusercontent.com/26837908/37009787-7a9dfe74-2123-11e8-9df9-0627ff22a3e2.png)
Not sure why but it allows me to load them

**Comment by Luffyyy** [comment]
I need some way to recreate this

**Comment by RexTheWho** [comment]
Unable to with the new UI from the looks of it.

**Comment by Luffyyy** [comment]
Alright. For now just use project+level method to load it and then replace it.
