### ISSUE TITLE
Assets UI not properly applying packages

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#63]
After loading in a new package, placing props down and then saving the map didnt seem to properly apply the added package.

In the Assets UI menu using the find package method doesnt add a package to the ingame list, but will to the main.xml
Note: Adding any other packages after that will override the last added package and cause loading issues. 
![image](https://user-images.githubusercontent.com/26837908/37027590-bea8b890-216c-11e8-9219-5ff8e17c94ee.png)

**Comment by Luffyyy** [comment]
Not sure exactly about this issue, I am adding packages and it adds them without any issue.

**Comment by RexTheWho** [comment]
Might be a false alarm, but if it pops up again Ill report it.
