### ISSUE TITLE
Editor is calling for an outdated update

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#65]
Launching with the latest beardlib editor asks to update and you get an outdated version.

**Comment by Nepgearsy** [comment]
that's because there's no version bump on mws side.

**Comment by RexTheWho** [comment]
Hmm... doesnt normally try to update for me, I guess somethings changed maybe

**Comment by Luffyyy** [comment]
The latest build in github was not pushed to mws, should be pushed now.
