### ISSUE TITLE
Semi-frequent "on_escape" crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#66]
Unsure on what exactly causes it but seems to only happen on the main menu.

Application has crashed: C++ exception
[string "--mods/BeardLib/Classes/Dialogs/MenuDialogMan..."]:102: attempt to call method 'on_escape' (a nil value)

SCRIPT STACK

func() @mods/BeardLib/Hooks/MenuManager.lua:20
core/lib/managers/controller/corecontrollerwrapper.lua:596

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                      IPHLPAPI  (???)     register_icmp                                       
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

**Comment by Luffyyy** [comment]
Fixed on latest BeardLib
