### ISSUE TITLE
Crash after 1-5s [crash.txt]

### ISSUE THREAD

**Issue by HoxHoxworth** [simon-wh/PAYDAY-2-BeardLib-Editor#7]
Circumstances:
- This is only when I run BeardLib and BeardLib-Editor in the mods folder together.
- I have disabled/uninstalled other mods with only these 2 running with the crash reccuring. [Including mod_overrides]
- I have disabled BeardLib-Editor with and without mods installed (not including BeardLib ofc) and I still crash.
- Running the game with all mods except BeardLib-Editor seems to work every time.

      Mods:
         1. BeardLib
         2. BeardLib-Editor [Cause of Crash]
         3. FreeFlightCamera
         4. RestorationMod
         5. PocoHud3
         6. Silent Assasin Mod
         7. WolfHUD
      
      At the time these were:
          1. Enabled
          2. Attempted Both
          3. Disabled
          4. Enabled
          5. Disabled
          6. Disabled
          7. Disabled
          8. Disabled

`Application has crashed: C++ exception
[string "lib/utils/game_state_machine/gamestatemachi..."]:601: attempt to index a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlFreeHeap                                         
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                         ntdll  (???)     wcstok_s                                            
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.68.209
	CPU : Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 950 / nvd3dum.dll[21.21.13.7849]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8079MB 332KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Logitech (Speakers (2- Logitech G430 Gaming Headset))

`

**Comment by Luffyyy** [comment]
Are you running the dev branch or master?

**Comment by HoxHoxworth** [comment]
At the moment, the master.

**Comment by HoxHoxworth** [comment]
Uhh.... I went in game and check the BeardLib Main Menu and there wasn't anything, anywhere about the editor like I've seen.

**Comment by Luffyyy** [comment]
Install beardLib dev as well.
