### ISSUE TITLE
custom/extract loaded units dont properly unload

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#71]
For example if I add a custom wall with a new texture to one heist and then I load into another heist it will still be loaded.

This also applies for overriding textures, if I for example retexture a vanilla unit and then load into a heist that uses the same unit it will still be applied.

**Comment by Luffyyy** [comment]
Dunno about textures(it's impossible to revert them, change the texture in material config) but I'll see about the units.

**Comment by Luffyyy** [comment]
Actually, give me a project to play with, from what I know, BeardLib **has** to unload them.

**Comment by Luffyyy** [comment]
Not sure at all what you mean, but for now: It's impossible to reload things except textures.
PackageManager:reload does nothing to material configs and I kinda assume it won't do much for units and objects plus it crashes some units sadly.

There's only Application:reload_textures which works for textures

**Comment by RexTheWho** [comment]
RE: That units not showing, its a different issue.
When you load a level then load to a different level occasionally units will not show in the load units from extract or normally as if they're already loaded.

**Comment by Luffyyy** [comment]
^That's fixed in the latest version.

**Comment by Luffyyy** [comment]
Due to actual limitations of the engine(from what I know currently) there's no way to reload anything that isn't a texture/script data.
