### ISSUE TITLE
spawning go through units

### ISSUE THREAD

**Issue by Nepgearsy** [simon-wh/PAYDAY-2-BeardLib-Editor#72]
https://i.imgur.com/B1QmOC1.png

like it ignores the collision or something

**Comment by Nepgearsy** [comment]
oh ok i just saw its the 'ruler' thing

is there any way to disable this?

**Comment by RexTheWho** [comment]
Pressing control will disable ruler snap.
In the controls pressing "Ctrl + R" toggles it off.
