### ISSUE TITLE
attempting to place a unit gets stuck

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#74]
Pressing ctrl will also reposition the unit but not follow your cursor.

![image](https://user-images.githubusercontent.com/26837908/37450308-666dcc76-2868-11e8-9410-d33e45c7addc.png)

**Comment by ontrigger** [comment]
@RexTheWho You can check out my fork for a different implementation of the spawning functionality. The marker should only move that way if you hold ctrl

**Comment by Luffyyy** [comment]
You didn't download the latest commit I assume.
