### ISSUE TITLE
Semi-Frequent unit crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#78]
When changing a unit to a different unit I crash, inconsistent but the 6th time it's happened today.
This also sometimes happens alt-dragging units also.
EDIT: This seems to only happen to extract loaded and custom added units

Application has crashed: C++ exception
[string "core/lib/system/coreengineaccess.lua"]:52: Failed to call hidden method PackageManager:editor_unit_data(...). Method not found.

SCRIPT STACK

_editor_unit_data() core/lib/system/coreengineaccess.lua:52
get_model_xml_file() core/lib/managers/coresequencemanager.lua:2040
get_xml_origin() core/lib/managers/coresequencemanager.lua:2028
print_vars() core/lib/managers/coresequencemanager.lua:1617
init() core/lib/managers/coresequencemanager.lua:1347
new() core/lib/utils/coreclass.lua:35
run_sequence() core/lib/managers/coresequencemanager.lua:2379
run_sequence() core/lib/managers/coresequencemanager.lua:380
run_sequence_simple3() core/lib/managers/coresequencemanager.lua:371
run_sequence_simple2() core/lib/managers/coresequencemanager.lua:366
_setup_variations() core/lib/utils/dev/editor/coreworlddefinition.lua:1049
assign_unit_data() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:433
_create_statics_unit() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:419
create_unit() @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:337
SpawnUnit() @mods/BeardLib-Editor/Classes/MapEditor.lua:310
clbk() @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:285
RunCallback() 365
SetValue() 355
TextBoxSetValue() 49
SetValue() 59
_callback() @mods/BeardLib-Editor/Classes/MenuUtils.lua:355
clbk() 167
RunCallback() 365
MousePressed() 72
MousePressed() 151
mouse_press() 376
lib/managers/mousepointermanager.lua:339

-------------------------------

**Comment by Nepgearsy** [comment]
I had this error in the past, the fix for it was to add the ``<extension name="damage" class="UnitDamage" />`` in the .unit

**Comment by RexTheWho** [comment]
This also occasionally happens with units that in vanilla dont seem to have it.
Example hcm_int_floor_1x1m_a_marble does not have it and I occasionally get crashes because I Alt dragged it.

**Comment by RexTheWho** [comment]
Unsure if anything on this has changed but its been a long time since this issue has happened.
