### ISSUE TITLE
Cannot add items to any element lists

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#79]
Cant add any units to the unit sequence element 
Cant connect elements
ect

**Comment by Luffyyy** [comment]
Explain

**Comment by RexTheWho** [comment]
Deleted both Beardlib and editor mods and redownloaded from github.

Still cannot link units or elements.
For example in a new map I attempt to connect a MissionScript to a PlayerSpawner in the Manage On Executed menu and it doesn't add it, I can remove stuff but not link anything.
