### ISSUE TITLE
Load Unit seems to have some font size issues

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#84]
Selecting units in the load unit list.
![image](https://user-images.githubusercontent.com/26837908/37593492-20dd1598-2bad-11e8-8c98-2109021aca00.png)

**Comment by Luffyyy** [comment]
You sure you got the latest beardlib from github?

**Comment by RexTheWho** [comment]
Deleted both Beardlib and editor mods and redownloaded from github.

Issue continues...
![image](https://user-images.githubusercontent.com/26837908/37636609-065d52aa-2c3e-11e8-9968-c8772c9f90a6.png)

**Comment by RexTheWho** [comment]
Additionally I suspect this is a related issue but in editor you cannot open the escape menu also.
