### ISSUE TITLE
Copy and pasting text issues

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#87]
Example, in unit sequence trigger Im adding "interact" to apply that trigger, but when I highlight, copy and paste it into another place, names, sequences, ect it pastes it twice and backspacing causes multiple letters to be removed at a time.

![image](https://user-images.githubusercontent.com/26837908/37692646-fe07fdd2-2cf4-11e8-8574-07288c4de4ff.png)

**Comment by Luffyyy** [comment]
Not sure about this issue I cannot reproduce it

**Comment by RexTheWho** [comment]
Seems constant to me.

https://puu.sh/zMVjJ/1211466bec.mp4
