### ISSUE TITLE
Element: Equipment given doesn't save.

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#88]
Equipment or Amount does not save, just deselecting and selecting it again will reset any changes.

Unsure if any other elements are broken at this time.

Edit: Just checked, Unit Sequence Trigger isnt saving changes either.

**Comment by Luffyyy** [comment]
Please confirm if last update fixed it.

**Comment by RexTheWho** [comment]
Fixed
