### ISSUE TITLE
+* and -* crash

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#93]
The select all remove all buttons often crash if there are too many elements or units to deal with.
Requesting something like an "are you sure" popup when more than 100 units/elements would be touched or for the buttons to be greyed out when too many units/elements are visible.

Bonus, seems trying to remove (-*) when some elements are selected (tested with the orientation_elements having 5 elements selected and 5 not selected) will just add more elements.

**Comment by Luffyyy** [comment]
Should be blazing fast next update(update beardlib also)
