### ISSUE TITLE
Elements being replaced issue

### ISSUE THREAD

**Issue by RexTheWho** [simon-wh/PAYDAY-2-BeardLib-Editor#96]
If I place down a startup element (id 100001)
And then swap to a different continent and place another element it will spawn as id 100001 and so on elements instead of adding onto the mission it replaces the old id.

This could be a pretty big and easy to accidentally do bug that can for example remove the startup element  and require the creator to completely relink every element again.

**Comment by Luffyyy** [comment]
Not getting this issue

**Comment by Luffyyy** [comment]
Any updates?

**Comment by RexTheWho** [comment]
Been some time since I had this issue, I think it's stopped happening since I know I've placed elements while the editor only cont was selected so this issue likely is done with for now.
